import {syntheticEdge} from './fixtures/protected-edge.js';
import {platformBinding,protectedWorkflowFetch} from '../../Core/src/workflow/protected-transport.js';
import {privateWorkflowRuntime} from '../../Core/src/workflow/private-runtime.js';
const vitestPath='../../Core/node_modules/vitest/dist/index.js';const {beforeAll,afterAll,describe,it,expect,vi}=await import(vitestPath);import {readFile,mkdtemp,unlink} from 'node:fs/promises';import {createServer} from 'node:https';import {connect} from 'node:net';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
import {neonConfig} from '../../Core/node_modules/@neondatabase/serverless';import {createHostedPool} from '../../Core/src/workflow/hosted-database.js';import {createPinnedWorkflowTransaction} from '../../Core/src/workflow/pinned-transaction.js';import {PostgresPacketStore} from '../../Core/src/workflow/postgres-store.js';import {GovernedPacketService} from '../../Core/src/workflow/packet-service.js';import {createHostedProjectRegistry,scopedRegistryQuery} from '../../Core/src/workflow/hosted-registry.js';import {profile,profileEnv} from '../../Core/tests/fixtures/hosted-profile.js';import {createOwnerAuth} from '../../Web/lib/owner-auth.js';import {createWorkflowOwnerVerifier} from '../../Web/lib/workflow-owner-verifier-host.js';import {hostedWorkflowRouter} from '../../Core/src/workflow/hosted-mount.js';import {createApp} from '../../Core/src/app.js';import {createTestConfig,TEST_DEVICE_TOKEN} from '../../Core/tests/test-config.js';import {actionBinding} from '../../Core/src/workflow/owner-delegation.js';
const root=process.env.BOB_HOSTED_NETWORK_FIXTURE,require=createRequire(import.meta.url),{WebSocketServer,WebSocket}=require('../../Web/node_modules/next/dist/compiled/ws');const password=profileEnv().BOB_WORKFLOW_DATABASE_PASSWORD;const p={ownerId:profile.owner.ownerId,actorId:profile.owner.actorId,projectKey:'bobai'};let port=0,cert:Buffer,server:ReturnType<typeof createServer>,wss:any,Socket:typeof globalThis.WebSocket,authPool:ReturnType<typeof createHostedPool>,registryPool:ReturnType<typeof createHostedPool>,pool:ReturnType<typeof createHostedPool>,cookie='',userId='';
async function admin(sql:string,params:unknown[]=[]){const rendered=sql.replace(/\$(\d+)/g,(_m,n:string)=>{const v=params[Number(n)-1];if(v===null)return 'NULL';if(typeof v==='number')return String(v);return "'"+String(v).replace(/'/g,"''")+"'";});const select=/^SELECT\b/i.test(rendered);const command=select?"SELECT COALESCE(json_agg(t),'[]') FROM ("+rendered+") t":rendered;const result=await promisify(execFile)('/usr/local/Cellar/postgresql@17/17.11/bin/psql',['-X','-At','-v','ON_ERROR_STOP=1','-h',process.env.BOB_LOCAL_WORKFLOW_TEST_SOCKET!,'-p',process.env.BOB_HOSTED_NETWORK_PORT!,'-U','bob_workflow_test_admin','-d','postgres','-c',command],{encoding:'utf8',env:{NODE_ENV:'test',PATH:'/usr/bin:/bin',PGPASSFILE:'/nonexistent',PGSERVICEFILE:'/dev/null'}});return {rows:select?JSON.parse(result.stdout.trim()):[]};}
const service=(revalidate=async()=>true)=>new GovernedPacketService(new PostgresPacketStore(createPinnedWorkflowTransaction(pool,profile.workflow,revalidate)));
describe.skipIf(!root)('actual isolated TLS WSS PostgreSQL and Better Auth hosted adapters',()=>{
 beforeAll(async()=>{
  if(!/^\/tmp\/bob-hosted-network-[A-Za-z0-9_-]+$/.test(root!))throw Error('owned_fixture_required');const marker=JSON.parse(await readFile(root+'/SYNTHETIC-ONLY.json','utf8'));expect(marker.kind).toBe('owned-hosted-network-fixture');expect((await admin("SELECT current_setting('data_directory') AS directory")).rows[0]?.directory).toBe(marker.data);
  for(const file of ['001_memory_v0_1.sql','002_shared_context_v0_2.sql','004_owner_auth.sql','governed/001_work_packets.sql','governed/002_policy_versions.sql','owner-delegation/001_proofs.sql','owner-delegation/002_project_versions.sql'])await admin(await readFile(new URL('../../Core/migrations/'+file,import.meta.url),'utf8'));
  for(const role of [profile.workflow.role,profile.registry.role,profile.auth.role])await admin(`CREATE ROLE ${role} LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD '${password}'`);
  await admin(`GRANT USAGE ON SCHEMA public,bob_workflow TO ${profile.workflow.role},${profile.registry.role}; GRANT SELECT ON ALL TABLES IN SCHEMA bob_workflow TO ${profile.workflow.role}; GRANT INSERT,UPDATE ON bob_workflow.packets TO ${profile.workflow.role};GRANT INSERT ON bob_workflow.records,bob_workflow.receipts,bob_workflow.history TO ${profile.workflow.role};GRANT USAGE ON ALL SEQUENCES IN SCHEMA bob_workflow TO ${profile.workflow.role};GRANT SELECT ON public.bob_projects,public.bob_tasks,public.bob_events TO ${profile.workflow.role};GRANT SELECT ON public.bob_projects,bob_workflow.grants TO ${profile.registry.role}; GRANT USAGE ON SCHEMA public,bob_owner_delegation TO ${profile.auth.role};GRANT INSERT,UPDATE,SELECT ON bob_owner_delegation.proofs TO ${profile.auth.role}`);
  const tables=(await admin("SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'bob_auth_%'")).rows;for(const t of tables)await admin(`GRANT SELECT,INSERT,UPDATE,DELETE ON public."${t.tablename}" TO ${profile.auth.role}`);
  await admin("INSERT INTO public.bob_projects(id,owner_id,project_key,name) VALUES($1,$2,'bobai','Synthetic network Bob Core')",[randomUUID(),p.ownerId]);await admin("INSERT INTO bob_workflow.projects(owner_id,project_key,policy,paused) VALUES($1,'bobai',NULL,false)",[p.ownerId]);await admin("INSERT INTO bob_workflow.grants(owner_id,project_key,actor_id,can_edit,can_review,enabled) VALUES($1,'bobai',$2,true,true,true)",[p.ownerId,p.actorId]);
  await promisify(execFile)('/usr/local/bin/openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',root+'/key.pem','-out',root+'/cert.pem','-subj','/CN='+profile.workflow.host,'-addext','subjectAltName=DNS:'+profile.workflow.host+',DNS:owner.example.invalid,DNS:core.example.invalid','-days','1']);cert=await readFile(root+'/cert.pem');server=createServer({key:await readFile(root+'/key.pem'),cert});wss=new WebSocketServer({noServer:true});server.on('upgrade',(req,s,head)=>{if(req.url!=='/v2'){s.destroy();return;}wss.handleUpgrade(req,s,head,(ws:any)=>{const db=connect({host:'127.0.0.1',port:Number(process.env.BOB_HOSTED_NETWORK_PORT)});db.on('data',d=>ws.readyState===1&&ws.send(d,{binary:true}));ws.on('message',(d:Buffer)=>db.write(d));db.on('error',()=>ws.close());db.on('close',()=>ws.close());ws.on('close',()=>db.destroy());ws.on('error',()=>db.destroy());});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));port=(server.address() as {port:number}).port;
  Socket=class extends WebSocket{constructor(url:string,protocol?:string){expect(url).toBe('wss://'+profile.workflow.host+'/v2');super('wss://127.0.0.1:'+port+'/v2',protocol,{ca:cert,servername:profile.workflow.host,rejectUnauthorized:true});}} as unknown as typeof globalThis.WebSocket;
  // Deny the SDK default transport: every connection must use our explicit local TLS Socket.
  neonConfig.wsProxy=()=>{throw Error('unexpected_default_network');};neonConfig.webSocketConstructor=class {constructor(){throw Error('unexpected_default_network');}} as unknown as typeof globalThis.WebSocket;
  for(const [k,v] of Object.entries(profileEnv()))vi.stubEnv(k,v);pool=createHostedPool(profile.workflow,password,Socket);registryPool=createHostedPool(profile.registry,password,Socket);authPool=createHostedPool(profile.auth,password,Socket);
  const auth=createOwnerAuth(authPool,true);const result=await auth.api.signUpEmail({body:{name:'Synthetic TLS owner',email:profile.owner.email,password:'synthetic-workflow-password'}});userId=result.user.id;await admin('UPDATE bob_auth_user SET "emailVerified"=true WHERE id=$1',[userId]);const signed=await auth.api.signInEmail({body:{email:profile.owner.email,password:'synthetic-workflow-password'},asResponse:true});cookie=signed.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');expect(cookie).toContain('session');
 },60000);
 afterAll(async()=>{await Promise.allSettled([pool?.end(),registryPool?.end(),authPool?.end()]);for(const c of wss?.clients??[])c.terminate();if(server)await new Promise<void>(r=>server.close(()=>r()));if(root)await Promise.allSettled([unlink(root+'/key.pem'),unlink(root+'/cert.pem')]);vi.unstubAllEnvs();});
 it('validates TLS identity and exact restricted role with actual driver',async()=>{expect((await pool.query('SELECT current_user AS role')).rows[0]?.role).toBe(profile.workflow.role);});
 it('rejects untrusted TLS certificate with no plaintext fallback',async()=>{const Bad=class extends WebSocket{constructor(_url:string,protocol?:string){super('wss://127.0.0.1:'+port+'/v2',protocol,{servername:profile.workflow.host,rejectUnauthorized:true});}} as unknown as typeof globalThis.WebSocket;const bad=createHostedPool(profile.workflow,password,Bad);try{await expect(bad.connect()).rejects.toThrow();}finally{await bad.end();}},15000);
 it('rejects TLS hostname mismatch even with trusted synthetic CA',async()=>{const Bad=class extends WebSocket{constructor(_url:string,protocol?:string){super('wss://127.0.0.1:'+port+'/v2',protocol,{ca:cert,servername:'wrong.example.invalid',rejectUnauthorized:true});}} as unknown as typeof globalThis.WebSocket;const bad=createHostedPool(profile.workflow,password,Bad);try{await expect(bad.connect()).rejects.toThrow();}finally{await bad.end();}},15000);
 it('enforces registry RLS scope and authorized directory',async()=>{const r=createHostedProjectRegistry(scopedRegistryQuery(registryPool));expect(await r.directory({...profile.owner,userId})).toEqual(['bobai']);expect(await r.directory({...profile.owner,userId,ownerId:'foreign'})).toEqual([]);expect(await r.project({...profile.owner,userId},'foreign')).toBeNull();});
 it('captures and retries once on actual pinned network transaction',async()=>{const c={operationId:'network-capture',packetId:'network-packet',action:'capture',expectedVersion:0,title:'Network synthetic capture',specification:'Durable criteria',predecessors:[]};const s=service();await s.command(p,c);await s.command(p,c);expect((await s.history(p)).items.filter(e=>e.operation_id===c.operationId)).toHaveLength(1);});
 it('rejects early END and comment control while rolling back all writes',async()=>{const tx=createPinnedWorkflowTransaction(pool,profile.workflow,async()=>true);for(const sql of ['END','/* comment */ COMMIT','COMMIT;SELECT 1'])await expect(tx(async q=>{await q("INSERT INTO bob_workflow.packets(owner_id,project_key,id,document) VALUES($1,$2,$3,$4::jsonb)\n            ON CONFLICT(owner_id,project_key,id) DO UPDATE SET document=EXCLUDED.document",[p.ownerId,p.projectKey,'rolled-back',JSON.stringify({})]);await q(sql,[]);})).rejects.toThrow();expect((await admin("SELECT count(*)::int AS n FROM bob_workflow.packets WHERE id='rolled-back'")).rows[0]?.n).toBe(0);});
 it('revocation after callback rolls back actual network write',async()=>{let calls=0;const s=service(async()=>++calls===1);await expect(s.command(p,{operationId:'denied-network',packetId:'denied-packet',action:'capture',expectedVersion:0,title:'Denied',specification:'Criteria',predecessors:[]})).rejects.toThrow();expect((await admin("SELECT count(*)::int AS n FROM bob_workflow.packets WHERE id='denied-packet'")).rows[0]?.n).toBe(0);});
 function verifier(){return createWorkflowOwnerVerifier(authPool,{issuer:profile.issuer,audience:profile.coreOrigin,owner:{...profile.owner,userId},proofLifetimeMs:60000},createHostedProjectRegistry(scopedRegistryQuery(registryPool)),{web:profileEnv().BOB_WORKFLOW_WEB_VERIFIER_CREDENTIAL,core:profileEnv().BOB_WORKFLOW_CORE_VERIFIER_CREDENTIAL});}
 const action=()=>actionBinding('GET','/v1/governed/bobai','','bobai');
 async function issue(bound=action()){const response=await verifier().request(profile.issuer+'/issue',{method:'POST',headers:{authorization:'Bearer '+profileEnv().BOB_WORKFLOW_WEB_VERIFIER_CREDENTIAL,cookie,'content-type':'application/json'},body:JSON.stringify({action:bound,audience:profile.coreOrigin})});expect(response.status).toBe(200);return (await response.json()).token;}
 async function redeem(token:string,a=action()){return verifier().request(profile.issuer+'/redeem',{method:'POST',headers:{authorization:'Bearer '+profileEnv().BOB_WORKFLOW_CORE_VERIFIER_CREDENTIAL,'content-type':'application/json'},body:JSON.stringify({token,action:a,audience:profile.coreOrigin})});}
 it('actual Better Auth session issues proof once and rejects replay',async()=>{const token=await issue();expect((await redeem(token)).status).toBe(200);expect((await redeem(token)).status).toBe(403);});
 it('rejects exact-request/cross-project confusion',async()=>{const token=await issue();expect((await redeem(token,{...action(),project:'foreign'})).status).toBe(403);expect((await redeem(token)).status).toBe(403);});
 it('authoritative grant revocation rejects issued proof',async()=>{const token=await issue();await admin("UPDATE bob_workflow.grants SET enabled=false WHERE owner_id=$1 AND project_key='bobai'",[p.ownerId]);expect((await redeem(token)).status).toBe(403);await admin("UPDATE bob_workflow.grants SET enabled=true WHERE owner_id=$1 AND project_key='bobai'",[p.ownerId]);});

 function mounted(factory:typeof createHostedPool=createHostedPool,network?:typeof fetch){const env={...profileEnv(),BOB_WORKFLOW_HOSTED_PROFILE:JSON.stringify({...profile,owner:{...profile.owner,userId}})};const router=hostedWorkflowRouter(env,{pool:(target,secret)=>factory(target,secret,Socket),network:network??(async(input,init)=>{const request=new Request(input as string,init);if(new URL(request.url).origin!==profile.issuer)throw Error('unexpected_network');return verifier().fetch(request);}) as typeof fetch});return createApp({config:createTestConfig(),aiProvider:{generate:async()=>({text:'unused',model:'test'})},governedRouter:router});}
 it('mounted owner route authenticates proof separately from legacy device middleware',async()=>{const app=mounted();expect((await app.request(profile.coreOrigin+'/v1/status')).status).toBe(401);const token=await issue();expect((await app.request(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token,'x-bob-owner-id':'foreign'}})).status).toBe(200);expect((await app.request(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token}})).status).toBe(403);expect((await app.request(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+TEST_DEVICE_TOKEN}})).status).toBe(403);});
 it('unknown COMMIT outcome reconciles and retries without duplicate advancement',async()=>{let lose=true;const factory:typeof createHostedPool=(target,secret,socket)=>{const x=createHostedPool(target,secret,socket);const connect=x.connect.bind(x);x.connect=(async()=>{const c=await connect();const query=c.query.bind(c);c.query=(async(sql:string,params:unknown[])=>{const result=await query(sql,params);if(sql==='COMMIT'&&lose){lose=false;throw Error('synthetic_commit_ack_lost');}return result;}) as typeof c.query;return c;}) as typeof x.connect;return x;};const app=mounted(factory);const command={operationId:'lost-network-ack',packetId:'lost-network-packet',action:'capture',expectedVersion:0,title:'Unknown outcome',specification:'Criteria',predecessors:[]};const body=JSON.stringify(command),bound=actionBinding('POST','/v1/governed/bobai/commands',body,'bobai');const first=await app.request(profile.coreOrigin+bound.path,{method:'POST',headers:{authorization:'Bearer '+await issue(bound),'content-type':'application/json'},body});expect(first.status).toBe(503);expect((await first.json()).outcome).toBe('unconfirmed');const retried=await app.request(profile.coreOrigin+bound.path,{method:'POST',headers:{authorization:'Bearer '+await issue(bound),'content-type':'application/json'},body});expect(retried.status).toBe(200);expect((await admin("SELECT count(*)::int AS n FROM bob_workflow.history WHERE operation_id='lost-network-ack'")).rows[0]?.n).toBe(1);const fresh=service();expect((await fresh.reconcile(p,command.operationId)).outcome).toBe('committed');});
 it('unavailable verifier denies before workflow database connection',async()=>{let connects=0;const app=mounted((target,secret,socket)=>{const x=createHostedPool(target,secret,socket);const original=x.connect.bind(x);x.connect=(async()=>{connects++;return original();}) as typeof x.connect;return x;},(async()=>{throw Error('synthetic_outage');}) as typeof fetch);const response=await app.request(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+'a'.repeat(64)}});expect(response.status).toBe(503);expect(connects).toBe(0);});

 const webBinding={issuer:'https://oidc.vercel.com/synthetic',audience:'https://vercel.com/synthetic',teamId:'team_synthetic',projectId:'prj_synthetic_web',environment:'preview'} as const;
 const coreBinding={...webBinding,projectId:'prj_synthetic_core'};
 let edge:ReturnType<typeof syntheticEdge>,privateApp:NonNullable<ReturnType<typeof privateWorkflowRuntime>>;
 let workflowConnections=0,failCommitAck=false;
 function httpsSetup(){
   const env={...profileEnv(),BOB_WORKFLOW_PRIVATE_RUNTIME_ENABLED:'true',BOB_WORKFLOW_PROTECTED_TRANSPORT_ENABLED:'true',BOB_WORKFLOW_PLATFORM_BINDING:JSON.stringify(coreBinding),BOB_WORKFLOW_HOSTED_PROFILE:JSON.stringify({...profile,owner:{...profile.owner,userId}})};
   edge=syntheticEdge(server,port,cert,profile,async request=>new URL(request.url).origin===profile.coreOrigin?privateApp.fetch(request):verifier().fetch(request),webBinding,coreBinding);
   const network=protectedWorkflowFetch(profile,platformBinding(env),()=>edge.jwt(coreBinding),edge.transport());
   const factory:typeof createHostedPool=(target,secret)=>{const x=createHostedPool(target,secret,Socket),connect=x.connect.bind(x);x.connect=(async()=>{workflowConnections++;const client=await connect(),query=client.query.bind(client);client.query=(async(sql:string,params:unknown[])=>{const value=await query(sql,params);if(sql==='COMMIT'&&failCommitAck){failCommitAck=false;throw Error('synthetic_https_commit_ack_lost');}return value;}) as typeof client.query;return client;}) as typeof x.connect;return x;};
   privateApp=privateWorkflowRuntime(env,()=>hostedWorkflowRouter(env,{pool:factory,network}))!;
 }
 function webNetwork(){return protectedWorkflowFetch(profile,webBinding,()=>edge.jwt(webBinding),edge.transport());}
 async function httpsIssue(bound=action()){const response=await webNetwork()(profile.issuer+'/issue',{method:'POST',headers:{authorization:'Bearer '+profileEnv().BOB_WORKFLOW_WEB_VERIFIER_CREDENTIAL,cookie,'content-type':'application/json'},body:JSON.stringify({action:bound,audience:profile.coreOrigin})});expect(response.status).toBe(200);return (await response.json()).token;}
 it('actual HTTPS protecting edge plus Better Auth/Core/PostgreSQL owner path',async()=>{httpsSetup();const token=await httpsIssue();const response=await webNetwork()(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token}});expect(response.status).toBe(200);expect((await response.json()).project.project_key).toBe('bobai');expect(edge.accepted()).toBeGreaterThanOrEqual(4);expect((await privateApp.request('/v1/chat')).status).toBe(404);});
 it('actual HTTPS edge independently denies wrong issuer/audience/project/expiry and forged signature',async()=>{const baseConnections=workflowConnections;for(const changes of [{iss:'https://foreign.invalid'},{aud:'foreign'},{project_id:'foreign'},{environment:'production'},{exp:1}]){const response=await edge.transport()(profile.issuer+'/issue',{method:'POST',headers:{'x-vercel-trusted-oidc-idp-token':edge.jwt(webBinding,changes)}});expect(response.status).toBe(403);}const real=edge.jwt(webBinding),parts=real.split('.'),signature=Buffer.from(parts[2]!,'base64url');signature[0]=signature[0]!^1;const response=await edge.transport()(profile.issuer+'/issue',{method:'POST',headers:{'x-vercel-trusted-oidc-idp-token':parts.slice(0,2).join('.')+'.'+signature.toString('base64url')}});expect(response.status).toBe(403);expect(workflowConnections).toBe(baseConnections);});
 it('actual HTTPS TLS refuses unknown CA and wrong hostname',async()=>{await expect(edge.transport({ca:Buffer.from('invalid')})(profile.issuer+'/issue',{method:'POST'})).rejects.toThrow();await expect(edge.transport({servername:'wrong.example.invalid'})(profile.issuer+'/issue',{method:'POST'})).rejects.toThrow();});
 it('actual HTTPS owner proof replay denied while workload identity is reusable',async()=>{const token=await httpsIssue();const call=()=>webNetwork()(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token}});expect((await call()).status).toBe(200);expect((await call()).status).toBe(403);expect((await webNetwork()(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+await httpsIssue()}})).status).toBe(200);});
 it('actual HTTPS rejects wrong project and missing owner authority',async()=>{const token=await httpsIssue();expect((await webNetwork()(profile.coreOrigin+'/v1/governed/foreign',{headers:{authorization:'Bearer '+token}})).status).toBe(403);expect((await webNetwork()(profile.coreOrigin+'/v1/governed/bobai')).status).toBe(403);});
 it('actual HTTPS redirects/outage fail closed without DB fallback',async()=>{const token=await httpsIssue(),start=workflowConnections;edge.setMode('redirect');try{await expect(webNetwork()(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token}})).rejects.toThrow('protected_redirect_denied');}finally{edge.setMode('normal');}edge.setMode('unavailable');try{expect((await webNetwork()(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token}})).status).toBe(503);}finally{edge.setMode('normal');}expect(workflowConnections).toBe(start);});
 it('actual HTTPS grant revocation blocks previously issued owner proof',async()=>{const token=await httpsIssue();await admin("UPDATE bob_workflow.grants SET enabled=false WHERE owner_id=$1 AND project_key='bobai'",[p.ownerId]);try{expect((await webNetwork()(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer '+token}})).status).toBe(403);}finally{await admin("UPDATE bob_workflow.grants SET enabled=true WHERE owner_id=$1 AND project_key='bobai'",[p.ownerId]);}});
 it('actual HTTPS lost commit acknowledgement retries once with fresh owner proof',async()=>{const command={operationId:'https-lost-ack',packetId:'https-packet',action:'capture',expectedVersion:0,title:'HTTPS synthetic',specification:'Receipt reconciliation',predecessors:[]},body=JSON.stringify(command),bound=actionBinding('POST','/v1/governed/bobai/commands',body,'bobai');const send=async()=>webNetwork()(profile.coreOrigin+bound.path,{method:'POST',headers:{authorization:'Bearer '+await httpsIssue(bound),'content-type':'application/json'},body});failCommitAck=true;const first=await send();expect(first.status).toBe(503);expect((await first.json()).outcome).toBe('unconfirmed');expect((await send()).status).toBe(200);expect((await admin("SELECT count(*)::int AS n FROM bob_workflow.history WHERE operation_id='https-lost-ack'")).rows[0]?.n).toBe(1);expect((await service().reconcile(p,'https-lost-ack')).outcome).toBe('committed');});
 it('expired current session rejects previously issued proof',async()=>{const token=await issue();await admin('UPDATE bob_auth_session SET "expiresAt"=now()-interval \'1 second\' WHERE "userId"=$1',[userId]);expect((await redeem(token)).status).toBe(403);});
});
