import {createHash,createPublicKey,verify} from 'node:crypto';import {z} from 'zod';
import {workflowPrincipal,type PacketPrincipal} from './packet-contract.js';import {privateTestingContextSchema,type PrivateTestingAuthority,type PrivateTestingReceipt} from './private-testing-evaluation.js';import {privateTestingDefinitions,privateTestingRequirementsDigest,privateTestingCheckCatalogDigest,requirementsDigest} from './private-testing-requirements.js';import {evidenceBodyDigest} from './scoped-evidence-source.js';
const id=z.string().regex(/^[A-Za-z0-9_-]{1,100}$/),sha=z.string().regex(/^[a-f0-9]{64}$/),count=z.number().int().min(0).max(100000),stamp=z.iso.datetime();
export const privateCheckContextSchema=z.object({context:privateTestingContextSchema,sourceDigest:sha,environmentDigest:sha,version:z.uuid(),expectedCases:z.record(z.string(),z.array(z.string().min(1).max(1000)).min(1).max(100000))}).strict();
const issuerSchema=z.object({id,keyId:id,actorId:id,approvalVersion:z.uuid(),ownerId:id,projectKey:id,enabled:z.literal(true),revoked:z.literal(false),expiresAt:z.number().int().positive(),publicKeyPem:z.string().min(20).max(8192),checks:z.array(z.object({id,definitionDigest:sha}).strict()).max(100)}).strict();
const binding={ownerId:id,projectKey:id,candidateId:id,candidateDigest:sha,environmentId:id,sourceDigest:sha,environmentDigest:sha,requirementsDigest:sha,catalogDigest:sha,checkId:id,definitionDigest:sha,procedureDigest:sha,caseInventoryDigest:sha,reportType:z.string().max(80)};
const claims=z.object({version:z.literal(1),...binding,runId:id,issuerId:id,keyId:id,issuerApprovalVersion:z.uuid(),reportDigest:sha,startedAt:stamp,completedAt:stamp,exitCode:z.number().int().nullable(),signal:z.string().max(80).nullable()}).strict();
export function privateCheckSigningBytes(v:unknown){return Buffer.from(JSON.stringify(['bobcore-private-check-v1',...Object.values(claims.parse(v))]));}
const blob=z.object({sha256:sha,bytesBase64:z.string().max(1400000)}).strict();
function bytes(v:z.infer<typeof blob>){const b=Buffer.from(v.bytesBase64,'base64');if(b.length>1048576||b.toString('base64')!==v.bytesBase64||createHash('sha256').update(b).digest('hex')!==v.sha256)throw Error('report_bytes_mismatch');return b;}
const nested=(v:z.infer<typeof blob>)=>JSON.parse(bytes(v).toString('utf8'));
export const privateCheckEnvelopeSchema=z.object({claims,signature:z.string().regex(/^[A-Za-z0-9_-]{86}$/),bytesBase64:blob.shape.bytesBase64}).strict();
const record=z.object({ownerId:id,projectKey:id,kind:z.enum(['context','issuer','report','manual']),id,version:z.uuid(),bodyDigest:sha,body:z.json()}).strict();
export interface PrivateCheckReader{authorized(p:PacketPrincipal):Promise<boolean>;read(p:PacketPrincipal,kind:'context'|'issuer'|'report'|'manual',id:string):Promise<unknown>;}
type Counts={executed:number;failed:number;skipped:number};
export function privateVitestCaseIds(raw:unknown):string[]{const r=raw as {testResults:Array<{name:string;assertionResults:Array<{fullName:string}>}>};const seen=new Map<string,number>();return r.testResults.flatMap(s=>s.assertionResults.map(a=>{const k=s.name+'::'+a.fullName,n=(seen.get(k)??0)+1;seen.set(k,n);return k+'#'+n;}));}
function vitest(raw:unknown):Counts{const s=z.object({numTotalTests:count,numPassedTests:count,numFailedTests:count,numPendingTests:count,success:z.boolean(),testResults:z.array(z.object({name:z.string().min(1).max(1000),assertionResults:z.array(z.object({fullName:z.string().min(1).max(1000),status:z.enum(['passed','failed','pending','todo','skipped'])})).max(100000)})).max(1000)}).parse(raw);const all=s.testResults.flatMap(x=>x.assertionResults);if(new Set(s.testResults.map(t=>t.name)).size!==s.testResults.length||all.length!==s.numTotalTests||all.filter(x=>x.status==='passed').length!==s.numPassedTests||all.filter(x=>x.status==='failed').length!==s.numFailedTests||all.filter(x=>!['passed','failed'].includes(x.status)).length!==s.numPendingTests||s.success!==(s.numFailedTests===0))throw Error('report_counts_mismatch');return {executed:s.numTotalTests-s.numPendingTests,failed:s.numFailedTests,skipped:s.numPendingTests};}
const continuityCases=['12 concurrent identical creates','conflicting operation payload','concurrent optimistic versions','restart and original-response replay','mutation/audit rollback','SIGKILL after commit before response and authorized replacement-client replay','owner/project/privacy/approval isolation','baseline independent of phrasing','stable context revision','separate handoff','two-project and Personal actual reads; missing/foreign project denial','bounded tasks/memories with truncation disclosure','active decisions only; proposals not activated; authority rule','missing memory dependency and injected decision-source outage disclosure'];
export const lifecycleCases=['already closed child does not skip database stop','exit before readiness rejects promptly and stops database','spawn failure cleanup reaches database stop','concurrent exit after readiness cleans safely','SIGTERM-resistant owned child gets bounded SIGKILL','readiness timeout still stops child and database','unsettleable child cleanup timeout cannot skip database stop','database stop failure retained with child cleanup failure'];
export function privateReportTimes(type:string,raw:unknown):{startedAt:string;completedAt:string}|null{
 const r=raw as Record<string,unknown>;let start:number|undefined,end:number|undefined;
 if(type==='vitest-v1'){const v=z.object({startTime:z.number().nonnegative().max(Number.MAX_SAFE_INTEGER),testResults:z.array(z.object({startTime:z.number().nonnegative().max(Number.MAX_SAFE_INTEGER),endTime:z.number().nonnegative().max(Number.MAX_SAFE_INTEGER)})).min(1)}).parse(raw);start=Math.floor(v.startTime);end=Math.ceil(Math.max(...v.testResults.map(t=>t.endTime)));if(v.testResults.some(t=>t.startTime<start!||t.endTime<t.startTime))throw Error('native_timestamps_invalid');}
 if(type==='playwright-runner-v1'){const v=z.object({stats:z.object({startTime:stamp,duration:z.number().nonnegative()})}).parse(raw);start=Date.parse(v.stats.startTime);end=start+Math.ceil(v.stats.duration);}
 if(type==='postgres-runner-v2'||type==='recovery-runner-v1'){const suites=(r.suites??[]) as Array<{report:z.infer<typeof blob>}>;const times=suites.map(s=>privateReportTimes('vitest-v1',nested(s.report)));if(times.length&&times.every(t=>t!==null)){start=Math.min(...times.map(t=>Date.parse(t!.startedAt)));end=Math.max(...times.map(t=>Date.parse(t!.completedAt)));}}
 if(start===undefined||end===undefined)return null;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||end<start)throw Error('native_timestamps_invalid');return {startedAt:new Date(start).toISOString(),completedAt:new Date(end).toISOString()};
}
function parseReport(check:typeof privateTestingDefinitions[number],raw:unknown,expected:string[]):Counts{
 const requireCases=(names:string[])=>{if(!expected.length||new Set(expected).size!==expected.length||JSON.stringify([...names].sort())!==JSON.stringify([...expected].sort()))throw Error('required_cases_mismatch');};
 if(check.reportType==='vitest-v1'){const n=vitest(raw);requireCases(privateVitestCaseIds(raw));return n;}
 if(check.reportType==='process-results-v1'){const r=z.object({version:z.literal(1),commands:z.array(z.object({argv:z.array(z.string().max(500)).max(30),exitCode:z.number().int().nullable(),signal:z.string().nullable(),stdout:blob,stderr:blob}).strict()).max(20)}).strict().parse(raw);const expected='commands' in check.procedure?check.procedure.commands:[];if(JSON.stringify(r.commands.map(c=>c.argv))!==JSON.stringify(expected))throw Error('procedure_commands_mismatch');for(const c of r.commands){bytes(c.stdout);bytes(c.stderr);}return {executed:r.commands.filter(c=>c.exitCode!==null).length,failed:r.commands.filter(c=>c.exitCode!==0||c.signal!==null).length,skipped:r.commands.filter(c=>c.exitCode===null).length};}
 if(check.reportType==='playwright-runner-v1'){const r=z.object({stats:z.object({expected:count,unexpected:count,skipped:count,flaky:count}),suites:z.array(z.unknown()).max(1000)}).parse(raw);const all:Array<{id:string;status:string;results:Array<{status:string}>}>=[];const walk=(v:unknown,depth=0)=>{if(depth>20)throw Error('report_depth');const s=z.object({suites:z.array(z.unknown()).optional(),specs:z.array(z.object({id:z.string().min(1),tests:z.array(z.object({projectId:z.string().max(200),status:z.enum(['expected','unexpected','skipped','flaky']),results:z.array(z.object({status:z.enum(['passed','failed','timedOut','skipped','interrupted'])})).max(10)}))})).optional()}).parse(v);for(const sp of s.specs??[])for(const t of sp.tests)all.push({id:sp.id+'/'+t.projectId,status:t.status,results:t.results});for(const sub of s.suites??[])walk(sub,depth+1);};for(const s of r.suites)walk(s);if(new Set(all.map(t=>t.id)).size!==all.length||(['expected','unexpected','skipped','flaky'] as const).some(k=>all.filter(t=>t.status===k).length!==r.stats[k])||all.some(t=>t.status==='expected'&&(t.results.length!==1||t.results[0]!.status!=='passed')))throw Error('browser_counts_mismatch');requireCases(all.map(t=>t.id));return {executed:all.filter(t=>t.status!=='skipped').length,failed:r.stats.unexpected+r.stats.flaky,skipped:r.stats.skipped};}
 if(check.reportType==='postgres-runner-v2'||check.reportType==='recovery-runner-v1'){const r=z.object({version:z.literal(1),privateSocket:z.literal(true),tcpDisabled:z.literal(true),fsync:z.literal(true),stopped:z.literal(true),suites:z.array(z.object({id:z.enum(['workflow','storage','private-records','recovery']),report:blob}).strict()).max(4)}).strict().parse(raw);const required=check.reportType==='postgres-runner-v2'?['workflow','storage','private-records','recovery']:['recovery'];if(JSON.stringify(r.suites.map(s=>s.id).sort())!==JSON.stringify(required.slice().sort()))throw Error('runner_suites_missing');const reports=r.suites.map(s=>({id:s.id,raw:nested(s.report)}));requireCases(reports.flatMap(s=>privateVitestCaseIds(s.raw).map(n=>s.id+':'+n)));return reports.reduce((a,s)=>{const b=vitest(s.raw);return {executed:a.executed+b.executed,failed:a.failed+b.failed,skipped:a.skipped+b.skipped};},{executed:0,failed:0,skipped:0});}
 if(check.reportType==='memory-continuity-v1'){const r=z.object({version:z.literal(1),continuity:blob,cold:blob,cleanup:blob,lifecycle:blob,privateSocket:z.literal(true),tcpDisabled:z.literal(true),fsync:z.literal(true),stopped:z.literal(true)}).strict().parse(raw);const persisted=z.object({memoryIds:z.array(z.uuid()).min(1),taskIds:z.array(z.uuid()).min(1),handoffId:z.uuid(),decisionIds:z.array(z.uuid()).min(1)}).strict();const c=z.object({passed:z.literal(true),syntheticLocalOnly:z.literal(true),checks:z.array(z.string()),persisted}).parse(nested(r.continuity));if(JSON.stringify(c.checks)!==JSON.stringify(continuityCases))throw Error('memory_cases_missing');const cold=z.object({passed:z.literal(true),coldDatabaseAndProcessRestart:z.literal(true),...persisted.shape}).parse(nested(r.cold));if(requirementsDigest(c.persisted)!==requirementsDigest({memoryIds:cold.memoryIds,taskIds:cold.taskIds,handoffId:cold.handoffId,decisionIds:cold.decisionIds}))throw Error('cold_ids_mismatch');const clean=z.object({passed:z.literal(true),syntheticOnly:z.literal(true),checks:z.array(z.object({mode:z.enum(['already-exited','failed-start','child-timeout']),databaseStopped:z.literal(true)}).strict())}).parse(nested(r.cleanup));if(JSON.stringify(clean.checks.map(c=>c.mode).sort())!==JSON.stringify(['already-exited','child-timeout','failed-start']))throw Error('cleanup_cases_missing');const life=z.object({version:z.literal(1),cases:z.array(z.object({id:z.string(),status:z.enum(['pass','fail','skipped'])}).strict())}).strict().parse(nested(r.lifecycle));if(JSON.stringify(life.cases.map(c=>c.id))!==JSON.stringify(lifecycleCases))throw Error('lifecycle_cases_missing');return {executed:18+life.cases.filter(c=>c.status!=='skipped').length,failed:life.cases.filter(c=>c.status==='fail').length,skipped:life.cases.filter(c=>c.status==='skipped').length};}
 throw Error('unsupported_check_format');
}
export function validatePrivateCheckObservations(checkId:string,raw:unknown,expectedCases:string[]){const check=privateTestingDefinitions.find(c=>c.id===checkId);if(!check||check.method!=='automated')throw Error('unsupported_check_format');return {counts:parseReport(check,raw,expectedCases),nativeTimes:privateReportTimes(check.reportType,raw)};}
export function privateManualSigningBytes(value:unknown){const m=value as Record<string,unknown>;return Buffer.from(JSON.stringify(['bobcore-private-manual-v1',evidenceBodyDigest({...m,certification:null})]));}
export function createPrivateCheckAuthority(reader?:PrivateCheckReader,clock=Date.now):PrivateTestingAuthority{
 async function read(p:PacketPrincipal,kind:z.infer<typeof record>['kind'],key:string){if(p.projectKey==='personal'||!reader||!await reader.authorized(p))throw Error('private_check_reader_unconfigured');const r=record.parse(await reader.read(p,kind,key));if(r.ownerId!==p.ownerId||r.projectKey!==p.projectKey||r.kind!==kind||r.id!==key||r.bodyDigest!==evidenceBodyDigest(r.body))throw Error('private_check_record_mismatch');return r.body;}
 const key=(c:string,e:string)=>c+'_'+e;async function ctx(p:PacketPrincipal,c:string,e:string){const x=privateCheckContextSchema.parse(await read(p,'context',key(c,e)));if(requirementsDigest(x.context.principal)!==requirementsDigest(p)||x.context.candidateId!==c||x.context.environmentId!==e||x.context.requirementsDigest!==privateTestingRequirementsDigest||x.context.catalogDigest!==privateTestingCheckCatalogDigest)throw Error('private_check_context_mismatch');return x;}
 return {async readContext(p,c,e){return (await ctx(workflowPrincipal.parse(p),c,e)).context;},async verifyCheck(p,c,e,checkId){p=workflowPrincipal.parse(p);const check=privateTestingDefinitions.find(x=>x.id===checkId);if(!check||!check.available)throw Error('private_check_unsupported');const first=await ctx(p,c,e);let receipt:PrivateTestingReceipt;let issuer:z.infer<typeof issuerSchema>|undefined;let completedAt:string;let admittedRecord:unknown;
 const receiptBase={ownerId:p.ownerId,projectKey:p.projectKey,candidateId:c,candidateDigest:first.context.candidateDigest,environmentId:e,requirementsDigest:privateTestingRequirementsDigest,catalogDigest:privateTestingCheckCatalogDigest,checkId,definitionDigest:check.definitionDigest,reportType:check.reportType};
 const base={ownerId:p.ownerId,projectKey:p.projectKey,candidateId:c,candidateDigest:first.context.candidateDigest,environmentId:e,sourceDigest:first.sourceDigest,environmentDigest:first.environmentDigest,requirementsDigest:privateTestingRequirementsDigest,catalogDigest:privateTestingCheckCatalogDigest,checkId,definitionDigest:check.definitionDigest,procedureDigest:requirementsDigest(check.procedure),caseInventoryDigest:requirementsDigest(first.expectedCases[checkId]??[]),reportType:check.reportType};
 if(check.method!=='automated'){
  const m=z.object({...binding,version:z.literal(1),method:z.enum(['independent_review','owner_walkthrough']),actorId:id,acceptanceVersion:z.uuid(),sourceTimestamp:stamp,recordDigest:sha,decision:z.enum(['accepted','rejected']),blockingFindings:count,authenticatedOwnerSession:z.boolean(),evidence:blob,certification:z.object({issuerId:id,keyId:id,approvalVersion:z.uuid(),signature:z.string().regex(/^[A-Za-z0-9_-]{86}$/)}).strict().nullable()}).strict().parse(admittedRecord=await read(p,'manual',key(c,e)+'_'+checkId));if(Object.keys(base).some(k=>(m as Record<string,unknown>)[k]!==base[k as keyof typeof base])||m.method!==check.method)throw Error('manual_binding_mismatch');
  if(check.method==='owner_walkthrough'?(m.actorId!==first.context.ownerActorId||!m.authenticatedOwnerSession||m.acceptanceVersion!==first.context.ownerWalkthroughVersion):(m.actorId===first.context.implementationActorId||m.acceptanceVersion!==first.context.independentReviewVersion))throw Error('manual_authority_mismatch');const validator=first.context.validator;if(!validator)throw Error('validator_unconfigured');if(m.recordDigest!==m.evidence.sha256)throw Error('manual_record_digest_mismatch');const ev=nested(m.evidence);if(evidenceBodyDigest(ev)!==evidenceBodyDigest({version:1,actorId:m.actorId,decision:m.decision,blockingFindings:m.blockingFindings}))throw Error('manual_record_invalid');if(check.method==='owner_walkthrough'){if(m.certification!==null)throw Error('owner_acceptance_not_validator');}else{const cert=m.certification;if(!cert)throw Error('review_certification_missing');issuer=issuerSchema.parse(await read(p,'issuer',cert.issuerId+'_'+cert.keyId));if(issuer.id!==validator.id||issuer.id!==cert.issuerId||issuer.actorId!==validator.actorId||issuer.approvalVersion!==validator.approvalVersion||cert.approvalVersion!==validator.approvalVersion||issuer.keyId!==cert.keyId||issuer.ownerId!==p.ownerId||issuer.projectKey!==p.projectKey||issuer.checks.filter(x=>x.id===checkId&&x.definitionDigest===check.definitionDigest).length!==1)throw Error('review_issuer_invalid');const pub=createPublicKey(issuer.publicKeyPem);if(pub.asymmetricKeyType!=='ed25519'||Buffer.from(cert.signature,'base64url').toString('base64url')!==cert.signature||!verify(null,privateManualSigningBytes(m),pub,Buffer.from(cert.signature,'base64url')))throw Error('review_signature_invalid');}completedAt=m.sourceTimestamp;receipt={...receiptBase,issuerId:check.method==='owner_walkthrough'?'owner-session-authority':validator.id,actorId:check.method==='owner_walkthrough'?m.actorId:validator.actorId,issuerApprovalVersion:validator.approvalVersion,method:check.method,sourceTimestamp:m.sourceTimestamp,reportDigest:m.recordDigest,provenanceVerified:true,outcome:m.decision==='accepted'&&!m.blockingFindings?'pass':'fail',failedCases:m.blockingFindings,skippedCases:0,executedCases:0,acceptanceVersion:m.acceptanceVersion};
 }else{
  const signed=privateCheckEnvelopeSchema.parse(admittedRecord=await read(p,'report',key(c,e)+'_'+checkId)),v=signed.claims,b=bytes({sha256:v.reportDigest,bytesBase64:signed.bytesBase64});if(Object.keys(base).some(k=>(v as Record<string,unknown>)[k]!==base[k as keyof typeof base]))throw Error('signed_check_binding_mismatch');issuer=issuerSchema.parse(await read(p,'issuer',v.issuerId+'_'+v.keyId));const validator=first.context.validator;if(!validator||issuer.id!==validator.id||issuer.actorId!==validator.actorId||issuer.approvalVersion!==validator.approvalVersion||issuer.id!==v.issuerId||issuer.keyId!==v.keyId||issuer.approvalVersion!==v.issuerApprovalVersion||issuer.ownerId!==p.ownerId||issuer.projectKey!==p.projectKey||issuer.checks.filter(x=>x.id===checkId&&x.definitionDigest===check.definitionDigest).length!==1)throw Error('private_check_issuer_mismatch');const pub=createPublicKey(issuer.publicKeyPem),sig=Buffer.from(signed.signature,'base64url');if(pub.asymmetricKeyType!=='ed25519'||sig.toString('base64url')!==signed.signature||!verify(null,privateCheckSigningBytes(v),pub,sig))throw Error('private_check_signature_invalid');const raw=JSON.parse(b.toString('utf8'));const native=privateReportTimes(check.reportType,raw);if(native&&(native.startedAt!==v.startedAt||native.completedAt!==v.completedAt))throw Error('native_execution_time_mismatch');const n=parseReport(check,raw,first.expectedCases[checkId]??[]);if(Date.parse(v.startedAt)>Date.parse(v.completedAt))throw Error('run_timestamps_invalid');if(v.exitCode!==0||v.signal!==null)n.failed=Math.max(n.failed,1);if(v.exitCode===null)n.skipped=Math.max(n.skipped,1);completedAt=v.completedAt;receipt={...receiptBase,issuerId:issuer.id,actorId:issuer.actorId,issuerApprovalVersion:issuer.approvalVersion,method:check.method,sourceTimestamp:completedAt,reportDigest:v.reportDigest,provenanceVerified:true,outcome:n.failed?'fail':n.skipped||!n.executed?'not_run':'pass',failedCases:n.failed,skippedCases:n.skipped,executedCases:n.executed,acceptanceVersion:null};
 }
 if(evidenceBodyDigest(await read(p,check.method==='automated'?'report':'manual',key(c,e)+'_'+checkId))!==evidenceBodyDigest(admittedRecord))throw Error('private_check_record_changed');
 if(issuer&&evidenceBodyDigest(await read(p,'issuer',issuer.id+'_'+issuer.keyId))!==evidenceBodyDigest(issuer))throw Error('private_check_issuer_changed');if(evidenceBodyDigest(await ctx(p,c,e))!==evidenceBodyDigest(first)||!reader||!await reader.authorized(p))throw Error('private_check_authority_changed');
 const now=clock();const validator=first.context.validator;if(!validator||!validator.enabled||validator.revoked||validator.expiresAt<=now||validator.ownerId!==p.ownerId||validator.projectKey!==p.projectKey||validator.actorId===first.context.implementationActorId)throw Error('validator_unconfigured_or_revoked');if(!Number.isSafeInteger(now)||now<0||Date.parse(completedAt)>now||issuer&&(issuer.expiresAt<=now||check.method==='automated'&&Date.parse(completedAt)+86400000<=now))throw Error('private_check_expired');return receipt;
 }};
}
