import {randomUUID} from 'node:crypto';import {z} from 'zod';
import {workflowPrincipal,WorkflowError,type PacketPrincipal} from './packet-contract.js';
import {actionBinding,type ActionBinding,type createOwnerDelegation} from './owner-delegation.js';
import {type PinnedPool,type IsolatedTarget} from './pinned-transaction.js';
import {evidenceBodyDigest} from './scoped-evidence-source.js';
import {privateCheckContextSchema,privateCheckEnvelopeSchema,validatePrivateCheckObservations,type PrivateCheckReader} from './private-check-adapters.js';
import {privateTestingDefinitions,privateTestingRequirementsDigest,privateTestingCheckCatalogDigest,requirementsDigest} from './private-testing-requirements.js';
const id=z.string().regex(/^[A-Za-z0-9_-]{1,100}$/),kind=z.enum(['context','issuer','report','manual']);
const inputSchema=z.object({operationId:id,candidateId:id,environmentId:id,checkId:id,envelope:privateCheckEnvelopeSchema}).strict();
const capabilities=new WeakMap<object,{principal:PacketPrincipal;action:ActionBinding;revalidate:()=>Promise<boolean>}>();
declare const capabilityBrand:unique symbol;export type PrivateRecordCapability={readonly [capabilityBrand]:true};
function deny(code:string):never{throw new WorkflowError(code,403);}
export async function resolvePrivateRecordCapability(verifier:Pick<ReturnType<typeof createOwnerDelegation>,'redeem'|'revalidate'>,token:string,action:ActionBinding):Promise<PrivateRecordCapability>{
 const prefix=`/v1/governed/${action.project}/private-checks`;if(action.project==='personal'||action.project==='_directory'||!(action.path===prefix||action.path.startsWith(prefix+'/')||action.path.startsWith(prefix+'?'))||!['GET','POST'].includes(action.method))deny('private_record_action_denied');
 const principals=z.array(workflowPrincipal).length(1).parse(await verifier.redeem(token,action));const principal=principals[0]!;if(principal.projectKey!==action.project)deny('private_record_scope_denied');
 const savedAction=Object.freeze({method:action.method,path:action.path,bodyDigest:action.bodyDigest,project:action.project}),cap=Object.freeze({}) as PrivateRecordCapability;capabilities.set(cap,{principal:Object.freeze(principal),action:savedAction,revalidate:async()=>{try{return await verifier.revalidate(token,savedAction)===true;}catch{return false;}}});return cap;
}
export function privateRecordPrincipal(cap:PrivateRecordCapability){const state=capabilities.get(cap);if(!state)deny('private_record_capability_unavailable');return state.principal;}
function scoped(cap:PrivateRecordCapability,purpose:'GET'|'POST'){const state=capabilities.get(cap);if(!state||state.action.method!==purpose||state.principal.projectKey==='personal')deny('private_record_capability_denied');return state;}
export type PrivateCaptureLimits={maxRecordsPerProject:number;maxStoredBytesPerProject:number};
export function createLocalPrivateRecordStore(pool:PinnedPool,target:IsolatedTarget,cap:PrivateRecordCapability,captureLimits?:PrivateCaptureLimits){
 const role=pool.options.user;if(process.env.VERCEL||target.kind!=='isolated-local'||!/^\/tmp\/bob-workflow-pg-[A-Za-z0-9_-]+$/.test(target.socket)||pool.options.host!==target.socket||pool.options.database!==target.database||role!==target.role||!['bob_private_reader_app','bob_private_capture_app'].includes(role??''))deny('private_record_database_unconfigured');
 const state=capabilities.get(cap);if(!state)deny('private_record_capability_unavailable');const p=state.principal;const limits=captureLimits?Object.freeze(z.object({maxRecordsPerProject:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),maxStoredBytesPerProject:z.number().int().positive().max(Number.MAX_SAFE_INTEGER)}).strict().parse(captureLimits)):null;if(state.action.method==='POST'&&!limits)deny('private_capture_capacity_unconfigured');
 async function transaction<T>(write:boolean,run:(q:import('./postgres-store.js').WorkflowQuery)=>Promise<T>){
  if(write?role!=='bob_private_capture_app':role!=='bob_private_reader_app')deny('private_record_role_denied');if(!await state!.revalidate())deny('private_record_access_denied');
  const c=await pool.connect();let begun=false,committing=false,poisoned=false;
  try{const row=(await c.query(`SELECT current_database() AS database,current_user AS role,session_user AS session_role,pg_backend_pid() AS pid,inet_server_addr()::text AS address,r.rolsuper,r.rolbypassrls,r.rolcreatedb,r.rolcreaterole FROM pg_roles r WHERE r.rolname=current_user`)).rows[0];
   if(!row||row.database!==target.database||row.role!==role||row.session_role!==role||row.address!==null||row.rolsuper!==false||row.rolbypassrls!==false||row.rolcreatedb!==false||row.rolcreaterole!==false)deny('private_record_database_target_mismatch');
   await c.query(write?'BEGIN':'BEGIN READ ONLY');begun=true;await c.query("SELECT set_config('bob.private_owner',$1,true),set_config('bob.private_project',$2,true),set_config('bob.private_actor',$3,true)",[p.ownerId,p.projectKey,p.actorId]);
   const result=await run(c.query);if((await c.query('SELECT pg_backend_pid() AS pid')).rows[0]?.pid!==row.pid)deny('private_record_connection_changed');if(!await state!.revalidate())deny('private_record_access_denied');
   committing=true;await c.query('COMMIT');begun=false;return result;
  }catch(e){poisoned=true;if(committing)throw new WorkflowError('private_capture_outcome_unconfirmed',503);if(begun){try{await c.query('ROLLBACK');}catch{throw new WorkflowError('private_record_rollback_unconfirmed',503);}}throw e;
  }finally{c.release(poisoned);}
 }
 async function authority(q:import('./postgres-store.js').WorkflowQuery){const r=(await q('SELECT version::text AS version,enabled FROM bob_private_checks.authorities WHERE owner_id=$1 AND project_key=$2',[p.ownerId,p.projectKey])).rows[0];if(!r||r.enabled!==true||!z.uuid().safeParse(r.version).success)deny('private_record_authority_unconfigured');return String(r.version);}
 async function record(q:import('./postgres-store.js').WorkflowQuery,k:z.infer<typeof kind>,key:string,version:string){const r=(await q('SELECT record_id::text AS version,body_digest,body FROM bob_private_checks.records WHERE owner_id=$1 AND project_key=$2 AND authority_version=$3::uuid AND kind=$4 AND logical_id=$5 ORDER BY sequence DESC LIMIT 1',[p.ownerId,p.projectKey,version,k,key])).rows[0];if(!r)return null;if(r.body_digest!==evidenceBodyDigest(r.body))deny('private_record_integrity_denied');return {ownerId:p.ownerId,projectKey:p.projectKey,kind:k,id:key,version:String(r.version),bodyDigest:String(r.body_digest),body:r.body};}
 const reader:PrivateCheckReader={async authorized(principal){return state!.action.method==='GET'&&role==='bob_private_reader_app'&&requirementsDigest(workflowPrincipal.parse(principal))===requirementsDigest(p)&&await state!.revalidate();},async read(principal,k,key){scoped(cap,'GET');if(requirementsDigest(workflowPrincipal.parse(principal))!==requirementsDigest(p))deny('private_record_scope_denied');kind.parse(k);id.parse(key);return transaction(false,async q=>{const version=await authority(q),r=await record(q,k,key,version);if(await authority(q)!==version)deny('private_record_authority_changed');return r;});}};
 return {reader,async capture(rawBody:string){scoped(cap,'POST');if(Buffer.byteLength(rawBody)>2*1024*1024)deny('private_capture_too_large');if(requirementsDigest(actionBinding('POST',`/v1/governed/${p.projectKey}/private-checks`,rawBody,p.projectKey))!==requirementsDigest(state!.action))deny('private_capture_action_mismatch');
  const input=inputSchema.parse(JSON.parse(rawBody)),logicalId=id.parse(input.candidateId+'_'+input.environmentId+'_'+input.checkId),contextId=id.parse(input.candidateId+'_'+input.environmentId),claims=input.envelope.claims;
  if(claims.ownerId!==p.ownerId||claims.projectKey!==p.projectKey||claims.candidateId!==input.candidateId||claims.environmentId!==input.environmentId||claims.checkId!==input.checkId)deny('private_capture_scope_denied');
  const report=Buffer.from(input.envelope.bytesBase64,'base64');if(!report.length||report.length>1048576||report.toString('base64')!==input.envelope.bytesBase64||claims.reportDigest!==importHash(report))deny('private_capture_bytes_denied');const check=privateTestingDefinitions.find(c=>c.id===input.checkId);if(!check||check.method!=='automated')deny('private_capture_check_denied');
  return transaction(true,async q=>{await q('SELECT pg_advisory_xact_lock(hashtextextended(jsonb_build_array($1::text,$2::text)::text,0))',[p.ownerId,p.projectKey]);const generation=await authority(q);const r=await record(q,'context',contextId,generation);if(!r)deny('private_capture_context_unavailable');const current=privateCheckContextSchema.parse(r.body),ctx=current.context;
   if(ctx.principal.ownerId!==p.ownerId||ctx.principal.projectKey!==p.projectKey||ctx.candidateId!==input.candidateId||ctx.environmentId!==input.environmentId||ctx.requirementsDigest!==privateTestingRequirementsDigest||ctx.catalogDigest!==privateTestingCheckCatalogDigest||claims.candidateDigest!==ctx.candidateDigest||claims.sourceDigest!==current.sourceDigest||claims.environmentDigest!==current.environmentDigest||claims.requirementsDigest!==ctx.requirementsDigest||claims.catalogDigest!==ctx.catalogDigest||claims.definitionDigest!==check.definitionDigest||claims.procedureDigest!==requirementsDigest(check.procedure)||claims.caseInventoryDigest!==requirementsDigest(current.expectedCases[input.checkId]??[])||claims.reportType!==check.reportType)deny('private_capture_binding_denied');
   const observations=validatePrivateCheckObservations(input.checkId,JSON.parse(report.toString('utf8')),current.expectedCases[input.checkId]??[]);if(observations.nativeTimes&&(observations.nativeTimes.startedAt!==claims.startedAt||observations.nativeTimes.completedAt!==claims.completedAt))deny('private_capture_execution_time_denied');
   const fingerprint=evidenceBodyDigest(input);await q('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[JSON.stringify([p.ownerId,p.projectKey,p.actorId,input.operationId])]);
   const old=(await q('SELECT authority_version::text AS authority_version,fingerprint,record_id::text AS record_id FROM bob_private_checks.capture_receipts WHERE owner_id=$1 AND project_key=$2 AND actor_id=$3 AND operation_id=$4',[p.ownerId,p.projectKey,p.actorId,input.operationId])).rows[0];
   if(old){if(old.authority_version!==generation||old.fingerprint!==fingerprint)deny('private_capture_operation_conflict');return {captureId:String(old.record_id),captured:true as const,certification:'unverified' as const,idempotent:true};}
   const usage=(await q("SELECT count(*)::text AS records,COALESCE(sum(octet_length(body::text)),0)::text AS bytes FROM bob_private_checks.records WHERE owner_id=$1 AND project_key=$2 AND kind='report'",[p.ownerId,p.projectKey])).rows[0];const size=(await q('SELECT octet_length(($1::jsonb)::text)::text AS bytes',[JSON.stringify(input.envelope)])).rows[0];if(!limits||!usage||!size||BigInt(String(usage.records))>=BigInt(limits.maxRecordsPerProject)||BigInt(String(usage.bytes))+BigInt(String(size.bytes))>BigInt(limits.maxStoredBytesPerProject))deny('private_capture_capacity_exceeded');
   const recordId=randomUUID();await q('INSERT INTO bob_private_checks.records(record_id,owner_id,project_key,authority_version,kind,logical_id,actor_id,body_digest,body) VALUES($1::uuid,$2,$3,$4::uuid,$5,$6,$7,$8,$9::jsonb)',[recordId,p.ownerId,p.projectKey,generation,'report',logicalId,p.actorId,evidenceBodyDigest(input.envelope),JSON.stringify(input.envelope)]);
   await q('INSERT INTO bob_private_checks.capture_receipts(owner_id,project_key,actor_id,operation_id,authority_version,fingerprint,record_id) VALUES($1,$2,$3,$4,$5::uuid,$6,$7::uuid)',[p.ownerId,p.projectKey,p.actorId,input.operationId,generation,fingerprint,recordId]);if(await authority(q)!==generation)deny('private_record_authority_changed');return {captureId:recordId,captured:true as const,certification:'unverified' as const,idempotent:false};
  });
 }};
}
import {createHash} from 'node:crypto';const importHash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
