import {describe,it,expect} from 'vitest';
import {syntheticEvidence} from '../scripts/lib/evidence-storage-fixture.js';
import {candidateDigest} from '../src/workflow/acceptance-contract.js';
import {projectEvidence,evidenceEffectiveExpiry} from '../src/workflow/evidence-projection.js';
import type {WorkPacket,WorkflowRecord} from '../src/workflow/packet-contract.js';
import type {WorkflowSnapshot} from '../src/workflow/postgres-store.js';
function fixture(){const f=syntheticEvidence(),now=Date.now(),packet:WorkPacket={id:f.claims.packetId,title:'Synthetic',specification:'criteria',specificationDigest:f.c.specificationDigest,predecessors:[],state:'draft',version:1,candidateId:f.c.id,candidateDigest:candidateDigest(f.c),updatedAt:new Date(now).toISOString()},record:WorkflowRecord={id:f.claims.id,packetId:packet.id,kind:'evidence',createdAt:new Date(now).toISOString(),content:{id:'durability',ownerId:f.p.ownerId,projectKey:f.p.projectKey,candidateDigest:packet.candidateDigest,issuer:'synthetic-ci',outcome:'pass',expiresAt:now+86400000,sourceRecordId:f.claims.sourceRecordId,sourceTimestamp:new Date(now).toISOString()}};const s:Pick<WorkflowSnapshot,'policy'|'records'|'now'>={now,policy:{versionId:'synthetic',digest:f.c.policyDigest,regressionDigest:f.c.regressionDigest,requiredChecks:['durability'],trustedIssuers:['synthetic-ci'],approvalLifetimeMs:60000,accepted:true},records:[{id:f.c.id,packetId:packet.id,kind:'candidate',createdAt:packet.updatedAt,content:f.c},record]};return {f,packet,record,s,run:()=>projectEvidence(s,f.p,packet)};}
describe('truthful read-only evidence projection, not new acceptance authority',()=>{
 it('reports legacy pass at server read without rewriting immutable history',()=>{const v=fixture(),before=JSON.stringify(v.s.records);expect(v.run().evidenceComplete).toBe(true);expect(v.run().checks[0]?.status).toBe('pass');expect(JSON.stringify(v.s.records)).toBe(before);});
 it.each(['policy','record','candidate'] as const)('blocks missing %s',what=>{const v=fixture();if(what==='policy')v.s.policy=null;if(what==='record')v.s.records=v.s.records.filter(r=>r.kind!=='evidence');if(what==='candidate'){v.packet.candidateId=null;v.packet.candidateDigest=null;}expect(v.run().evidenceComplete).toBe(false);expect(v.run().checks[0]?.status).toBe(what==='policy'?'policy_missing':'missing');});
 it.each(['expired','untrusted','failed','not_run','future','verification_pending','invalid'] as const)('blocks and accurately labels %s',what=>{const v=fixture();if(what==='expired')v.record.content.expiresAt=v.s.now;if(what==='untrusted')v.record.content.issuer='foreign';if(what==='failed')v.record.content.outcome='fail';if(what==='not_run')v.record.content.outcome='not_run';if(what==='future')v.record.content.sourceTimestamp=new Date(v.s.now+1).toISOString();if(what==='verification_pending')v.record.content.verification={reportDigest:'a'.repeat(64)};if(what==='invalid')v.record.content.ownerId='foreign';expect(v.run().evidenceComplete).toBe(false);expect(v.run().checks[0]?.status).toBe(what==='future'?'invalid':what);});
 it('bounds source freshness at exactly24h despite later legacy expiry',()=>{const v=fixture();v.record.content.sourceTimestamp=new Date(v.s.now-86400000).toISOString();expect(v.run().checks[0]?.status).toBe('expired');expect(v.run().evidenceComplete).toBe(false);});
 it('blocks ambiguous records and changed candidate policy, keeping history untouched',()=>{const v=fixture();v.s.records.push({...v.record,id:'another'});expect(v.run().checks[0]?.status).toBe('ambiguous');const w=fixture();w.s.policy!.digest='0'.repeat(64);expect(w.run().checks[0]?.status).toBe('candidate_changed');expect(w.run().evidenceComplete).toBe(false);});
 it('shares exact24h expiry and invalid future completion between server gate and UI projection',()=>{const now=Date.now();expect(evidenceEffectiveExpiry({expiresAt:now+2*86400000,sourceTimestamp:new Date(now-86400000).toISOString()},now)).toBe(now);expect(evidenceEffectiveExpiry({expiresAt:now+86400000,sourceTimestamp:new Date(now+1).toISOString()},now)).toBe(0);});

});
