import {describe,it,expect} from 'vitest';
import {localOwnerDirection,localOwnerDirectionDigest,evaluateDirectionEvidence,type DirectionEvidenceContext} from '../src/workflow/owner-policy-direction.js';
const now=Date.parse('2026-10-01T06:00:00Z'),a='a'.repeat(64),b='b'.repeat(64),c='c'.repeat(64);
const input={ownerId:'synthetic-owner',projectKey:'bobai',candidateDigest:a,policyDigest:b,baselineDigest:c,issuer:'synthetic-test-issuer',sourceTimestamp:new Date(now).toISOString(),outcome:'pass'};
const context:DirectionEvidenceContext={ownerId:'synthetic-owner',projectKey:'bobai',candidateDigest:a,policyDigest:b,directionDigest:localOwnerDirectionDigest,acceptedBaselineDigest:c,trustedIssuerIds:['synthetic-test-issuer']};
describe('owner-approved direction with unselected real authority fail closed',()=>{
 it('records exact approved local direction without approval validity, spending or deletion authority',()=>{expect(localOwnerDirection).toMatchObject({approvalAuthority:'owner_only',proofLifetimeMs:60000,evidenceLifetimeMs:86400000,decisionHistory:'permanent',evidenceHistory:'permanent',temporarySecurityDiagnosticsDays:7,encryptedBackupIntervalMs:86400000,encryptedBackupRetentionDays:30,recoveryTargetMs:7200000,activationAllowed:false});expect(localOwnerDirection).not.toHaveProperty('approvalLifetimeMs');expect(localOwnerDirection).not.toHaveProperty('spendingCap');expect(Object.isFrozen(localOwnerDirection)).toBe(true);});
 it('rejects missing authority, baseline and issuer with no fallback',()=>{expect(evaluateDirectionEvidence(input)).toEqual({allowed:false,reason:'authoritative_policy_unavailable'});expect(evaluateDirectionEvidence(input,{...context,acceptedBaselineDigest:""})).toEqual({allowed:false,reason:'accepted_baseline_unconfigured'});expect(evaluateDirectionEvidence(input,{...context,trustedIssuerIds:[]})).toEqual({allowed:false,reason:'trusted_issuer_unconfigured'});});
 it('bounds exact unchanged evidence to24h from authenticated completion rather than ingestion',()=>{expect(evaluateDirectionEvidence(input,context,now+86400000-1)).toEqual({allowed:true,expiresAt:now+86400000,directionDigest:localOwnerDirectionDigest});expect(evaluateDirectionEvidence(input,context,now+86400000)).toEqual({allowed:false,reason:'evidence_not_current'});});
 it.each(['candidateDigest','policyDigest','baselineDigest'])('invalidates changed %s immediately',key=>{expect(evaluateDirectionEvidence({...input,[key]:'d'.repeat(64)},context,now)).toEqual({allowed:false,reason:'candidate_or_policy_changed'});});
 it.each(['ownerId','projectKey'])('rejects wrong %s',key=>{expect(evaluateDirectionEvidence({...input,[key]:'synthetic-other'},context,now)).toEqual({allowed:false,reason:'evidence_scope_mismatch'});});
 it('rejects unselected issuer, future source time and old policy version',()=>{expect(evaluateDirectionEvidence({...input,issuer:'synthetic-worker'},context,now)).toEqual({allowed:false,reason:'evidence_issuer_untrusted'});expect(evaluateDirectionEvidence({...input,sourceTimestamp:new Date(now+1).toISOString()},context,now)).toEqual({allowed:false,reason:'evidence_not_current'});expect(evaluateDirectionEvidence(input,{...context,directionDigest:'d'.repeat(64)},now)).toEqual({allowed:false,reason:'owner_direction_version_mismatch'});});
});
