import {describe,it,expect} from 'vitest';import {randomUUID} from 'node:crypto';import {createOwnerDelegation,actionBinding,type OwnerProof,type OwnerProofStore} from '../src/workflow/owner-delegation.js';
const owner={ownerId:'owner',actorId:'actor',userId:'user',email:'owner@example.invalid'},action=actionBinding('POST','/v1/governed/bobai/commands','{}','bobai');
function fixture(){let time=1000,stage='';const session:any={user:{id:owner.userId,email:owner.email,emailVerified:true},session:{id:'session',userId:owner.userId,expiresAt:new Date(10000),updatedAt:new Date(0)}};let advance:(point:string)=>void=()=>{};let proof:OwnerProof|null=null,consumed=false;const version=randomUUID();const store:OwnerProofStore={async insert(_h,p){proof=p;advance('insert');},async consume(){if(consumed)return null;consumed=true;advance('consume');return proof;},async consumed(){advance('consumed');return consumed?proof:null;}};
 const verifier=createOwnerDelegation({issuer:'http://127.0.0.1:3433',audience:'http://127.0.0.1:3431',owner,proofLifetimeMs:1000},{api:{async getSession(){advance('getSession');return session;}},async currentSession(){advance('currentSession');return session;}},{async directory(){advance('directory');return ['bobai'];},async project(_o,key){advance('project');return {ownerId:owner.ownerId,actorId:owner.actorId,projectKey:key,active:true,enabled:true,revoked:false,authorityVersion:version};}},store,()=>time);
 return {verifier,session,store,setTime:(t:number)=>time=t,on:(f:(p:string)=>void)=>advance=f,getProof:()=>proof};
}
describe('owner delegation expiry after awaited authority reads',()=>{
 it.each(['currentSession','project','directory'])('denies exact proof expiry during last %s read',async point=>{const f=fixture();const a=point==='directory'?actionBinding('GET','/v1/governed/projects','','_directory'):action;const t=await f.verifier.issue(new Headers(),a);await f.verifier.redeem(t.token,a);f.on(p=>{if(p===point)f.setTime(2000);});expect(await f.verifier.revalidate(t.token,a)).toBe(false);});
 it.each(['currentSession','project','directory'])('denies session expiry during %s read even if proof stays future',async point=>{const f=fixture();const a=point==='directory'?actionBinding('GET','/v1/governed/projects','','_directory'):action;const t=await f.verifier.issue(new Headers(),a);await f.verifier.redeem(t.token,a);f.session.session.expiresAt=new Date(1500);f.on(p=>{if(p===point)f.setTime(1500);});expect(await f.verifier.revalidate(t.token,a)).toBe(false);});
 it('rejects expiry during redemption grant read, burns single use',async()=>{const f=fixture(),t=await f.verifier.issue(new Headers(),action);f.on(p=>{if(p==='project')f.setTime(2000);});await expect(f.verifier.redeem(t.token,action)).rejects.toThrow('owner_delegation_denied');f.setTime(1000);await expect(f.verifier.redeem(t.token,action)).rejects.toThrow('owner_delegation_denied');});
 it.each(['getSession','project','directory','insert'])('does not return token after session expiry during issue %s',async point=>{const f=fixture();f.session.session.expiresAt=new Date(1500);f.on(p=>{if(p===point)f.setTime(1500);});const a=point==='directory'?actionBinding('GET','/v1/governed/projects','','_directory'):action;await expect(f.verifier.issue(new Headers(),a)).rejects.toThrow('owner_delegation_denied');});
 it('does not return token if proof expires during storage insertion',async()=>{const f=fixture();f.on(p=>{if(p==='insert')f.setTime(2000);});await expect(f.verifier.issue(new Headers(),action)).rejects.toThrow('owner_delegation_denied');expect(f.getProof()?.expiresAt).toBe(2000);});
 it('accepts exactly one millisecond before final proof expiry',async()=>{const f=fixture(),t=await f.verifier.issue(new Headers(),action);await f.verifier.redeem(t.token,action);f.on(p=>{if(p==='project')f.setTime(1999);});expect(await f.verifier.revalidate(t.token,action)).toBe(true);});
 it.each([NaN,Infinity,-1,1000.5])('invalid final clock %s fails closed',async time=>{const f=fixture(),t=await f.verifier.issue(new Headers(),action);await f.verifier.redeem(t.token,action);f.on(p=>{if(p==='project')f.setTime(time);});expect(await f.verifier.revalidate(t.token,action)).toBe(false);});
});
