import {describe,it,expect} from 'vitest';import {resolvePrivateRecordCapability,privateRecordPrincipal,createLocalPrivateRecordStore,type PrivateRecordCapability} from '../src/workflow/private-record-store.js';import {actionBinding} from '../src/workflow/owner-delegation.js';
const p={ownerId:'owner',actorId:'actor',projectKey:'bobai'},target={kind:'isolated-local' as const,socket:'/tmp/bob-workflow-pg-unit',database:'postgres',role:'bob_private_reader_app'};
const action=actionBinding('GET','/v1/governed/bobai/private-checks','','bobai');
function fixture(){let calls=0;const v={redeem:async()=>[p],revalidate:async()=>true};const pool={options:{host:target.socket,database:'postgres',user:target.role},connect:async()=>{calls++;throw Error('must not connect');}};return {v,pool,calls:()=>calls};}
describe('local private-record capability boundary',()=>{
 it('resolves opaque capability only through exact owner-proof redemption',async()=>{const f=fixture(),c=await resolvePrivateRecordCapability(f.v,'synthetic',action);expect(privateRecordPrincipal(c)).toEqual(p);expect(JSON.stringify(c)).toBe('{}');expect(()=>createLocalPrivateRecordStore(f.pool,target,{} as PrivateRecordCapability)).toThrow('private_record_capability_unavailable');expect(f.calls()).toBe(0);});
 it.each(['personal','_directory'])('denies %s before redemption',async project=>{const f=fixture();await expect(resolvePrivateRecordCapability(f.v,'synthetic',{...action,project})).rejects.toThrow();});
 it('denies lookalike path and mismatched/ambiguous principal',async()=>{const f=fixture();await expect(resolvePrivateRecordCapability(f.v,'synthetic',{...action,path:action.path+'-other'})).rejects.toThrow();f.v.redeem=async()=>[{...p,projectKey:'other'}];await expect(resolvePrivateRecordCapability(f.v,'synthetic',action)).rejects.toThrow();});
 it.each(['host','database','user'])('rejects changed %s before evidence connection',async field=>{const f=fixture(),c=await resolvePrivateRecordCapability(f.v,'synthetic',action);(f.pool.options as Record<string,string>)[field]='wrong';expect(()=>createLocalPrivateRecordStore(f.pool,target,c)).toThrow('private_record_database_unconfigured');expect(f.calls()).toBe(0);});
 it('denies revoked/unavailable owner authority before connection',async()=>{const f=fixture(),c=await resolvePrivateRecordCapability(f.v,'synthetic',action);const s=createLocalPrivateRecordStore(f.pool,target,c);f.v.revalidate=async()=>false;await expect(s.reader.read(p,'context','candidate_fixture')).rejects.toThrow('private_record_access_denied');f.v.revalidate=async()=>{throw Error('unavailable');};await expect(s.reader.read(p,'context','candidate_fixture')).rejects.toThrow('private_record_access_denied');expect(f.calls()).toBe(0);});
 it('reader cannot capture and wrong-project reads cannot connect',async()=>{const f=fixture(),c=await resolvePrivateRecordCapability(f.v,'synthetic',action),s=createLocalPrivateRecordStore(f.pool,target,c);await expect(s.capture('{}')).rejects.toThrow('private_record_capability_denied');await expect(s.reader.read({...p,projectKey:'other'},'context','candidate_fixture')).rejects.toThrow('private_record_scope_denied');expect(f.calls()).toBe(0);});
 it('capture proof cannot authorize different bytes or return read authority',async()=>{const f=fixture();f.pool.options.user='bob_private_capture_app';const c=await resolvePrivateRecordCapability(f.v,'synthetic',actionBinding('POST',action.path,'{}','bobai')),s=createLocalPrivateRecordStore(f.pool,{...target,role:'bob_private_capture_app'},c,{maxRecordsPerProject:4,maxStoredBytesPerProject:1048576});await expect(s.capture('{ }')).rejects.toThrow('private_capture_action_mismatch');expect(await s.reader.authorized(p)).toBe(false);expect(f.calls()).toBe(0);});
});
