import {describe,it,expect} from 'vitest';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {readFile} from 'node:fs/promises';
import {localBootstrapOperator} from '../scripts/local-private-bootstrap.mjs';
const root=process.env.BOB_HOSTED_NETWORK_FIXTURE;
describe.skipIf(!root)('actual owned empty bootstrap rollback and restore',()=>{
 let operator;
 it('refuses absent/mismatched ownership marker before SQL',async()=>{await expect(localBootstrapOperator('/tmp/not-owned')).rejects.toThrow();await expect(localBootstrapOperator(root,{...process.env,BOB_HOSTED_NETWORK_PORT:'1'})).rejects.toThrow();operator=await localBootstrapOperator(root);await operator.sql('CREATE DATABASE bob_bootstrap_empty');});
 it('injected bundle failure leaves no schemas or roles',async()=>{await expect(operator.bootstrap('bob_bootstrap_empty',true)).rejects.toThrow();expect(await operator.sql("SELECT count(*) FROM pg_tables WHERE schemaname NOT IN ('pg_catalog','information_schema')",'bob_bootstrap_empty')).toBe('0');expect(await operator.sql("SELECT count(*) FROM pg_roles WHERE rolname LIKE 'rehearsal_%'")).toBe('0');});
 it('pins migrations and provisions no-login least-privilege roles without owner grants',async()=>{await operator.bootstrap('bob_bootstrap_empty');expect(operator.manifest.migrations).toHaveLength(8);expect(await operator.sql("SELECT count(*) FROM pg_roles WHERE rolname LIKE 'rehearsal_%' AND NOT rolsuper AND NOT rolbypassrls AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolcanlogin")).toBe('3');expect(await operator.sql('SELECT count(*) FROM bob_workflow.grants','bob_bootstrap_empty')).toBe('0');expect(await operator.sql("SELECT has_table_privilege('rehearsal_workflow','bob_workflow.grants','UPDATE')",'bob_bootstrap_empty')).toBe('f');expect(await operator.sql("SELECT has_table_privilege('rehearsal_registry','bob_workflow.packets','INSERT')",'bob_bootstrap_empty')).toBe('f');});
 it('retry refuses initialized target rather than resetting history',async()=>{await expect(operator.bootstrap('bob_bootstrap_empty')).rejects.toThrow('target_not_empty');await operator.sql("INSERT INTO bob_workflow.projects(owner_id,project_key) VALUES('synthetic','bobai')",'bob_bootstrap_empty');await expect(operator.bootstrap('postgres')).rejects.toThrow();expect(await operator.sql('SELECT count(*) FROM bob_workflow.projects','bob_bootstrap_empty')).toBe('1');});
 it('dump/restore keeps target data, RLS and denied role authority; no destructive down rollback',async()=>{const path=root+'/workflow-validation/bootstrap.dump',args=['-h',operator.marker.socket,'-p',String(operator.marker.port),'-U','bob_workflow_test_admin'];await promisify(execFile)(operator.bin+'/pg_dump',[...args,'-Fc','-f',path,'bob_bootstrap_empty'],{env:operator.clean});await operator.sql('CREATE DATABASE bob_bootstrap_restored');await promisify(execFile)(operator.bin+'/pg_restore',[...args,'-d','bob_bootstrap_restored','--exit-on-error',path],{env:operator.clean});expect(await operator.sql('SELECT count(*) FROM bob_workflow.projects','bob_bootstrap_restored')).toBe('1');expect(await operator.sql("SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='bob_workflow.projects'::regclass",'bob_bootstrap_restored')).toBe('t');expect(await operator.sql("SELECT has_table_privilege('rehearsal_workflow','bob_workflow.grants','UPDATE')",'bob_bootstrap_restored')).toBe('f');expect((await readFile(path)).length).toBeGreaterThan(0);});
});
