import {describe,it,expect} from 'vitest';import {generateKeyPairSync,sign,randomUUID,createHash} from 'node:crypto';
import {createPrivateCheckAuthority,privateCheckSigningBytes,privateManualSigningBytes,privateVitestCaseIds,privateReportTimes,lifecycleCases,type PrivateCheckReader} from '../src/workflow/private-check-adapters.js';import {evidenceBodyDigest} from '../src/workflow/scoped-evidence-source.js';import {privateTestingDefinitions as defs,privateTestingRequirementsDigest as rd,privateTestingCheckCatalogDigest as cd,requirementsDigest} from '../src/workflow/private-testing-requirements.js';import {evaluatePrivateTestingRequirements} from '../src/workflow/private-testing-evaluation.js';
const p={ownerId:'synthetic-owner',projectKey:'bobai',actorId:'owner-actor'},cid='candidate',eid='fixture',now=Date.now();const keys=generateKeyPairSync('ed25519');export const blob=(v:unknown)=>{const b=Buffer.from(typeof v==='string'?v:JSON.stringify(v));return {sha256:createHash('sha256').update(b).digest('hex'),bytesBase64:b.toString('base64')};};
const vt=(status='passed')=>({startTime:now-2000,numTotalTests:1,numPassedTests:status==='passed'?1:0,numFailedTests:status==='failed'?1:0,numPendingTests:!['passed','failed'].includes(status)?1:0,success:status!=='failed',testResults:[{name:'synthetic-file',startTime:now-2000,endTime:now-1000,assertionResults:[{fullName:'required-case',status}]}]});
function fixture(){const approval=randomUUID();const ctx:any={context:{principal:p,requirementsDigest:rd,catalogDigest:cd,candidateId:cid,candidateDigest:'a'.repeat(64),environmentId:eid,contextVersion:randomUUID(),implementationActorId:'implementer',ownerActorId:p.actorId,validator:{id:'validator',actorId:'validator-actor',ownerId:p.ownerId,projectKey:p.projectKey,approvalVersion:approval,enabled:true,revoked:false,expiresAt:now+86400000},independentReviewVersion:randomUUID(),ownerWalkthroughVersion:randomUUID(),candidateOwnerAccepted:false,environmentAuthorized:false},sourceDigest:'b'.repeat(64),environmentDigest:'c'.repeat(64),version:randomUUID(),expectedCases:{'core-regression':['synthetic-file::required-case#1'],'actual-auth-web':['browser-case/'],'governed-postgres':['workflow:synthetic-file::required-case#1','storage:synthetic-file::required-case#1','private-records:synthetic-file::required-case#1','recovery:synthetic-file::required-case#1'],'encrypted-recovery':['recovery:synthetic-file::required-case#1']}};const issuer:any={id:'validator',keyId:'key',actorId:'validator-actor',approvalVersion:approval,ownerId:p.ownerId,projectKey:p.projectKey,enabled:true,revoked:false,expiresAt:now+86400000,publicKeyPem:keys.publicKey.export({type:'spki',format:'pem'}).toString(),checks:defs.map(c=>({id:c.id,definitionDigest:c.definitionDigest}))};const records=new Map<string,any>();let authorized=true;const read:PrivateCheckReader={authorized:async()=>authorized,read:async(q,kind,id)=>{const body=kind==='context'?ctx:kind==='issuer'?issuer:records.get(id);return {ownerId:p.ownerId,projectKey:p.projectKey,kind,id,version:randomUUID(),bodyDigest:evidenceBodyDigest(body),body};}};
 const base=(check:any)=>({ownerId:p.ownerId,projectKey:p.projectKey,candidateId:cid,candidateDigest:ctx.context.candidateDigest,environmentId:eid,sourceDigest:ctx.sourceDigest,environmentDigest:ctx.environmentDigest,requirementsDigest:rd,catalogDigest:cd,checkId:check.id,definitionDigest:check.definitionDigest,procedureDigest:requirementsDigest(check.procedure),caseInventoryDigest:requirementsDigest(ctx.expectedCases[check.id]??[]),reportType:check.reportType});
 const report=(id:string,raw:any,mutate:(v:any)=>void=()=>{})=>{const c=defs.find(c=>c.id===id)!;const b=blob(raw),claims:any={version:1,...base(c),runId:'run',issuerId:'validator',keyId:'key',issuerApprovalVersion:approval,reportDigest:b.sha256,startedAt:new Date(now-2000).toISOString(),exitCode:0,signal:null,completedAt:new Date(now-1000).toISOString()};let native;try{native=privateReportTimes(c.reportType,raw);}catch{/* Deliberately signed malformed fixture must reach adapter denial. */}if(native)Object.assign(claims,native);mutate(claims);const e={claims,signature:sign(null,privateCheckSigningBytes(claims),keys.privateKey).toString('base64url'),bytesBase64:b.bytesBase64};records.set(cid+'_'+eid+'_'+id,e);return e;};
 const manual=(id:string,change:(m:any)=>void=()=>{})=>{const c=defs.find(c=>c.id===id)!;const m:any={version:1,...base(c),method:c.method,actorId:c.method==='owner_walkthrough'?p.actorId:'independent-reviewer',acceptanceVersion:c.method==='owner_walkthrough'?ctx.context.ownerWalkthroughVersion:ctx.context.independentReviewVersion,sourceTimestamp:new Date(now-1000).toISOString(),recordDigest:'d'.repeat(64),decision:'accepted',blockingFindings:0,authenticatedOwnerSession:c.method==='owner_walkthrough',evidence:blob({}),certification:null};change(m);m.evidence=blob({version:1,actorId:m.actorId,decision:m.decision,blockingFindings:m.blockingFindings});m.recordDigest=m.evidence.sha256;if(c.method==='independent_review')m.certification={issuerId:'validator',keyId:'key',approvalVersion:approval,signature:sign(null,privateManualSigningBytes(m),keys.privateKey).toString('base64url')};records.set(cid+'_'+eid+'_'+id,m);return m;};
 const parse=(id:string)=>createPrivateCheckAuthority(read,()=>now).verifyCheck(p,cid,eid,id);return {ctx,issuer,records,read,report,manual,parse,revoke:()=>{authorized=false;}};
}
const browser=()=>({stats:{startTime:new Date(now-2000).toISOString(),duration:1000,expected:1,unexpected:0,skipped:0,flaky:0},suites:[{specs:[{id:'browser-case',tests:[{projectId:'',status:'expected',results:[{status:'passed'}]}]}]}]});const pg=(ids:string[])=>({version:1,privateSocket:true,tcpDisabled:true,fsync:true,stopped:true,suites:ids.map(id=>({id,report:blob(vt())}))});
const memoryCases=['12 concurrent identical creates','conflicting operation payload','concurrent optimistic versions','restart and original-response replay','mutation/audit rollback','SIGKILL after commit before response and authorized replacement-client replay','owner/project/privacy/approval isolation','baseline independent of phrasing','stable context revision','separate handoff','two-project and Personal actual reads; missing/foreign project denial','bounded tasks/memories with truncation disclosure','active decisions only; proposals not activated; authority rule','missing memory dependency and injected decision-source outage disclosure'];
function memory(){const persisted={memoryIds:[randomUUID()],taskIds:[randomUUID()],handoffId:randomUUID(),decisionIds:[randomUUID()]};return {version:1,continuity:blob({passed:true,syntheticLocalOnly:true,checks:memoryCases,persisted}),cold:blob({passed:true,coldDatabaseAndProcessRestart:true,...persisted}),cleanup:blob({passed:true,syntheticOnly:true,checks:['already-exited','failed-start','child-timeout'].map(mode=>({mode,databaseStopped:true}))}),lifecycle:blob({version:1,cases:lifecycleCases.map(id=>({id,status:'pass'}))}),privateSocket:true,tcpDisabled:true,fsync:true,stopped:true};}
describe('authenticated private-check adapters — synthetic issuer only',()=>{
 it.each(['core-types-build','web-types-build'])('binds exact process argv %s',async id=>{const f=fixture(),c=defs.find(c=>c.id===id)!;f.report(id,{version:1,commands:('commands' in c.procedure?c.procedure.commands:[]).map(argv=>({argv,exitCode:0,signal:null,stdout:blob(''),stderr:blob('')}))});expect((await f.parse(id) as any).outcome).toBe('pass');});
 it.each(['core-regression','actual-auth-web','governed-postgres','encrypted-recovery','memory-continuity'])('parses bound %s format',async id=>{const f=fixture();f.report(id,id==='core-regression'?vt():id==='actual-auth-web'?browser():id==='memory-continuity'?memory():pg(id==='encrypted-recovery'?['recovery']:['workflow','storage','private-records','recovery']));expect((await f.parse(id) as any).outcome).toBe('pass');});
 it.each(['failed','pending','skipped','todo'])('never converts %s to pass',async status=>{const f=fixture();f.report('core-regression',vt(status));expect((await f.parse('core-regression') as any).outcome).not.toBe('pass');});
 it.each(['ownerId','projectKey','candidateId','candidateDigest','environmentId','sourceDigest','environmentDigest','requirementsDigest','catalogDigest','definitionDigest','procedureDigest','caseInventoryDigest','reportType'])('denies signed wrong %s',async field=>{const f=fixture();f.report('core-regression',vt(),v=>v[field]=field.endsWith('Digest')?'e'.repeat(64):'other');await expect(f.parse('core-regression')).rejects.toThrow();});
 it('denies forged signature/raw flag/tampered bytes/missing source',async()=>{const f=fixture(),e=f.report('core-regression',vt());e.signature='A'.repeat(86);await expect(f.parse('core-regression')).rejects.toThrow();f.records.set(cid+'_'+eid+'_core-regression',{provenanceVerified:true});await expect(f.parse('core-regression')).rejects.toThrow();const g=fixture(),x=g.report('core-regression',vt());x.bytesBase64=blob(vt('failed')).bytesBase64;await expect(g.parse('core-regression')).rejects.toThrow();g.records.clear();await expect(g.parse('core-regression')).rejects.toThrow();});
 it.each(['revoked','enabled','expiresAt','actorId','ownerId','projectKey','approvalVersion','publicKeyPem'])('denies issuer %s',async field=>{const f=fixture();f.report('core-regression',vt());f.issuer[field]=field==='revoked'?true:field==='enabled'?false:field==='expiresAt'?now:field==='approvalVersion'?randomUUID():'wrong';await expect(f.parse('core-regression')).rejects.toThrow();});
 it('denies missing/duplicate allowed check',async()=>{for(const dup of [false,true]){const f=fixture();f.report('core-regression',vt());const c=f.issuer.checks.find((c:any)=>c.id==='core-regression');f.issuer.checks=dup?[c,c]:[];await expect(f.parse('core-regression')).rejects.toThrow();}});
 it.each([-1,NaN,Infinity])('denies invalid clock %s',async clock=>{const f=fixture();f.report('core-regression',vt());await expect(createPrivateCheckAuthority(f.read,()=>clock).verifyCheck(p,cid,eid,'core-regression')).rejects.toThrow();});
 it.each([now+1,now-86400000])('denies future/expired receipt %s',async t=>{const f=fixture();f.report('core-regression',vt(),v=>v.completedAt=new Date(t).toISOString());await expect(f.parse('core-regression')).rejects.toThrow();});
 it('uses final clock after final authority read',async()=>{const f=fixture();f.report('core-regression',vt());let time=now,n=0;const old=f.read.read;f.read.read=async(...a)=>{const v=await old(...a);if(a[1]==='context'&&++n===2)time=now+86400000;return v;};await expect(createPrivateCheckAuthority(f.read,()=>time).verifyCheck(p,cid,eid,'core-regression')).rejects.toThrow();});
 it('denies context change and access revocation after report read',async()=>{for(const revoke of [true,false]){const f=fixture();f.report('core-regression',vt());const old=f.read.read;let n=0;f.read.read=async(...a)=>{if(a[1]==='context'&&++n===2){if(revoke)f.revoke();else f.ctx.version=randomUUID();}return old(...a);};await expect(f.parse('core-regression')).rejects.toThrow();}});
 it('denies partial/unknown/duplicate/summary-spoofed cases',async()=>{for(const raw of [{passed:true},{...vt(),numTotalTests:2},{...vt(),testResults:[{name:'synthetic-file',startTime:now-2000,endTime:now-1000,assertionResults:[{fullName:'wrong',status:'passed'}]}]},{...vt(),numTotalTests:2,numPassedTests:2,testResults:[{name:'synthetic-file',startTime:now-2000,endTime:now-1000,assertionResults:[{fullName:'required-case',status:'passed'},{fullName:'required-case',status:'passed'}]}]}]){const f=fixture();f.report('core-regression',raw);await expect(f.parse('core-regression')).rejects.toThrow();}});
 it.each(['missing-suite','tcp-on','not-stopped','tampered'])('denies incomplete PG %s',async mode=>{const f=fixture(),r=pg(['workflow','storage','private-records','recovery']);if(mode==='missing-suite')r.suites.pop();if(mode==='tcp-on')r.tcpDisabled=false;if(mode==='not-stopped')r.stopped=false;if(mode==='tampered')r.suites[0]!.report.sha256='f'.repeat(64);f.report('governed-postgres',r);await expect(f.parse('governed-postgres')).rejects.toThrow();});
 it.each(['cold','cleanup','lifecycle','continuity'])('denies missing memory subrecord %s',async field=>{const f=fixture(),r:any=memory();delete r[field];f.report('memory-continuity',r);await expect(f.parse('memory-continuity')).rejects.toThrow();});
 it.each(['independent-security-review','owner-walkthrough'])('requires separate authenticated manual %s',async id=>{const f=fixture();f.manual(id);expect((await f.parse(id) as any).outcome).toBe('pass');const g=fixture();g.report(id,vt());await expect(g.parse(id)).rejects.toThrow();});
 it('requires distinct review author and validator certification',async()=>{const f=fixture();f.manual('independent-security-review',m=>m.actorId='implementer');await expect(f.parse('independent-security-review')).rejects.toThrow();const g=fixture(),m=g.manual('independent-security-review');m.certification=null;await expect(g.parse('independent-security-review')).rejects.toThrow();});
 it.each(['stale','actor','session','bytes'])('denies invalid owner record %s',async mode=>{const f=fixture(),m=f.manual('owner-walkthrough');if(mode==='stale')m.acceptanceVersion=randomUUID();if(mode==='actor')m.actorId='validator-actor';if(mode==='session')m.authenticatedOwnerSession=false;if(mode==='bytes')m.evidence=blob({decision:'accepted'});await expect(f.parse('owner-walkthrough')).rejects.toThrow();});
 it('does not invent manual 24h acceptance validity',async()=>{for(const id of ['owner-walkthrough','independent-security-review']){const f=fixture();f.manual(id,m=>m.sourceTimestamp=new Date(now-3*86400000).toISOString());expect((await f.parse(id) as any).outcome).toBe('pass');}});
 it('unconfigured reader/unknown check fail closed; candidate remains unaccepted',async()=>{await expect(createPrivateCheckAuthority().readContext(p,cid,eid)).rejects.toThrow();const f=fixture();await expect(f.parse('unknown')).rejects.toThrow();const r=await evaluatePrivateTestingRequirements(p,{candidateId:cid,environmentId:eid},createPrivateCheckAuthority(f.read),()=>now);expect(r.eligible).toBe(false);expect(r.activationAllowed).toBe(false);});
 it('parses deterministic multi-case report formats without local retained receipts',async()=>{
  const f=fixture();const raw=browser();raw.stats.expected=31;raw.suites[0]!.specs=Array.from({length:31},(_,i)=>({id:'synthetic-browser-'+i,tests:[{projectId:'',status:'expected',results:[{status:'passed'}]}]}));
  f.ctx.expectedCases['actual-auth-web']=raw.suites[0]!.specs.map(s=>s.id+'/');f.report('actual-auth-web',raw);expect((await f.parse('actual-auth-web') as any).executedCases).toBe(31);
  const old=pg(['workflow','storage','recovery']);f.report('governed-postgres',old);await expect(f.parse('governed-postgres')).rejects.toThrow('runner_suites_missing');
  const recovery=vt();recovery.numTotalTests=recovery.numPassedTests=5;recovery.testResults[0]!.assertionResults=Array.from({length:5},(_,i)=>({fullName:'synthetic-recovery-'+i,status:'passed'}));f.ctx.expectedCases['encrypted-recovery']=privateVitestCaseIds(recovery).map(id=>'recovery:'+id);f.report('encrypted-recovery',{version:1,privateSocket:true,tcpDisabled:true,fsync:true,stopped:true,suites:[{id:'recovery',report:blob(recovery)}]});expect((await f.parse('encrypted-recovery') as any).executedCases).toBe(5);
 });
 it.each(['counts','skipped','flaky','interrupted'])('browser %s cannot pass',async mode=>{const f=fixture(),r=browser();if(mode==='counts')r.stats.expected=2;else if(mode==='interrupted')r.suites[0]!.specs[0]!.tests[0]!.results[0]!.status='interrupted';else{r.stats.expected=0;r.stats[mode as 'skipped'|'flaky']=1;r.suites[0]!.specs[0]!.tests[0]!.status=mode;}f.report('actual-auth-web',r);let result:unknown;try{result=await f.parse('actual-auth-web');}catch{return;}expect((result as any).outcome).not.toBe('pass');});
 it.each(['argv','signal','exit','missing'])('process %s cannot pass',async mode=>{const f=fixture(),c=defs.find(c=>c.id==='core-types-build')!;const commands=('commands' in c.procedure?c.procedure.commands:[]).map(argv=>({argv:[...argv] as string[],exitCode:0 as number|null,signal:null as string|null,stdout:blob(''),stderr:blob('')}));if(mode==='argv')commands[0]!.argv=['wrong'];if(mode==='signal')commands[0]!.signal='SIGTERM';if(mode==='exit')commands[0]!.exitCode=1;if(mode==='missing')commands.pop();f.report(c.id,{version:1,commands});let result:unknown;try{result=await f.parse(c.id);}catch{return;}expect((result as any).outcome).not.toBe('pass');});

 it.each(['nonzero','signal','no-exit','reversed-time'])('signed runner %s cannot pass',async mode=>{const f=fixture();f.report('core-regression',vt(),v=>{if(mode==='nonzero')v.exitCode=1;if(mode==='signal')v.signal='SIGTERM';if(mode==='no-exit')v.exitCode=null;if(mode==='reversed-time')v.startedAt=new Date(now).toISOString();});let result:unknown;try{result=await f.parse('core-regression');}catch{return;}expect((result as any).outcome).not.toBe('pass');});
 it.each(['disabled','revoked','expired','implementer'])('current validator %s is denied independently of stale key row',async mode=>{const f=fixture();f.report('core-regression',vt());if(mode==='disabled')f.ctx.context.validator.enabled=false;if(mode==='revoked')f.ctx.context.validator.revoked=true;if(mode==='expired')f.ctx.context.validator.expiresAt=now;if(mode==='implementer')f.ctx.context.implementationActorId=f.ctx.context.validator.actorId;await expect(f.parse('core-regression')).rejects.toThrow();});
 it('immutable repeated reads are verification only; wrong project/outer hash and reader outage deny',async()=>{const f=fixture();f.report('core-regression',vt());expect(await f.parse('core-regression')).toEqual(await f.parse('core-regression'));const old=f.read.read;f.read.read=async(...a)=>{const r=await old(...a) as any;return {...r,projectKey:'other'};};await expect(f.parse('core-regression')).rejects.toThrow();const g=fixture();g.report('core-regression',vt());g.read.read=async()=>{throw Error('unavailable');};await expect(g.parse('core-regression')).rejects.toThrow();});

 it('all nine adapters compose with strict evaluator but cannot accept candidate/environment',async()=>{const f=fixture();for(const c of defs){if(c.method!=='automated'){f.manual(c.id);continue;}const raw=c.reportType==='process-results-v1'?{version:1,commands:('commands' in c.procedure?c.procedure.commands:[]).map(argv=>({argv,exitCode:0,signal:null,stdout:blob(''),stderr:blob('')}))}:c.reportType==='vitest-v1'?vt():c.reportType==='playwright-runner-v1'?browser():c.reportType==='memory-continuity-v1'?memory():pg(c.reportType==='recovery-runner-v1'?['recovery']:['workflow','storage','private-records','recovery']);f.report(c.id,raw);}const r=await evaluatePrivateTestingRequirements(p,{candidateId:cid,environmentId:eid},createPrivateCheckAuthority(f.read,()=>now),()=>now);expect(r.checks).toHaveLength(9);expect(r.checks.every(c=>c.status==='pass')).toBe(true);expect(r.reason).toBe('candidate_owner_acceptance_required');expect(r.eligible).toBe(false);expect(r.activationAllowed).toBe(false);});
 it('signed source replacement during verification cannot reuse prior admitted record',async()=>{const f=fixture();f.report('core-regression',vt());const old=f.read.read;let n=0;f.read.read=async(...a)=>{if(a[1]==='report'&&++n===2)f.report('core-regression',vt('failed'));return old(...a);};await expect(f.parse('core-regression')).rejects.toThrow();});

 it('native execution dates cannot be relabelled by a fresh signature',async()=>{const f=fixture();f.report('core-regression',vt(),v=>{v.startedAt=new Date(now-3000).toISOString();});await expect(f.parse('core-regression')).rejects.toThrow();const g=fixture();g.report('core-regression',vt(),v=>{v.completedAt=new Date(now).toISOString();});await expect(g.parse('core-regression')).rejects.toThrow();});

});
