import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {privateTestingRequirements as req,privateTestingRequirementsDigest as reqDigest,privateTestingCheckCatalog as catalog,privateTestingCheckCatalogDigest as catDigest,privateTestingDefinitions as definitions} from '../src/workflow/private-testing-requirements.js';
import {evaluatePrivateTestingRequirements as evaluate,type PrivateTestingAuthority,type PrivateTestingContext,type PrivateTestingReceipt} from '../src/workflow/private-testing-evaluation.js';
const p={ownerId:'synthetic-owner',projectKey:'bobai',actorId:'synthetic-owner-actor'},request={candidateId:'synthetic-candidate',environmentId:'owned-fixture'},now=Date.now();
function fixture(){
 const context:PrivateTestingContext={principal:p,requirementsDigest:reqDigest,catalogDigest:catDigest,candidateId:request.candidateId,candidateDigest:'a'.repeat(64),environmentId:request.environmentId,contextVersion:randomUUID(),implementationActorId:'synthetic-implementer',ownerActorId:p.actorId,validator:{id:'synthetic-validator',actorId:'synthetic-validator-actor',ownerId:p.ownerId,projectKey:p.projectKey,approvalVersion:randomUUID(),enabled:true,revoked:false,expiresAt:now+2*86400000},independentReviewVersion:randomUUID(),ownerWalkthroughVersion:randomUUID(),candidateOwnerAccepted:false,environmentAuthorized:false};
 const reports=new Map<string,PrivateTestingReceipt>();
 for(const check of definitions)reports.set(check.id,{ownerId:p.ownerId,projectKey:p.projectKey,candidateId:context.candidateId,candidateDigest:context.candidateDigest,environmentId:context.environmentId,requirementsDigest:reqDigest,catalogDigest:catDigest,checkId:check.id,definitionDigest:check.definitionDigest,issuerId:check.method==='owner_walkthrough'?'owner-session-authority':context.validator!.id,actorId:check.method==='owner_walkthrough'?context.ownerActorId:context.validator!.actorId,issuerApprovalVersion:context.validator!.approvalVersion,method:check.method,reportType:check.reportType,sourceTimestamp:new Date(now-1000).toISOString(),reportDigest:'b'.repeat(64),provenanceVerified:true,outcome:'pass',failedCases:0,skippedCases:0,executedCases:check.method==='automated'?1:0,acceptanceVersion:check.method==='independent_review'?context.independentReviewVersion:check.method==='owner_walkthrough'?context.ownerWalkthroughVersion:null});
 const calls:string[]=[];const authority:PrivateTestingAuthority={readContext:async()=>context,verifyCheck:async(_p,_c,_e,id)=>{calls.push(id);return reports.get(id)??null;}};
 const run=()=>evaluate(p,request,authority,()=>now);
 return {context,reports,calls,authority,run};
}
describe('approved private-testing summary and unmounted fail-closed requirements catalog',()=>{
 it('records exactly owner summary approval, never candidate/live/issuer acceptance or unseen PB protection',()=>{expect(req.approval.ownerMessage).toBe('Sentinel_6b322d5e11888191be6f3fb99fdc5eec');expect(req.requirementsApproved).toBe(true);expect(req.candidateAccepted).toBe(false);expect(req.liveSetupApproved).toBe(false);expect(req.protectedPBDetailsAccepted).toBe(false);expect(req.validator.identity).toBeNull();expect(req.validator.publicKey).toBeNull();expect(req.statements).toHaveLength(5);expect(req.requirements.some(r=>r.description.includes('fallback'))).toBe(false);expect(req.requirements.some(r=>r.description.includes('decision'))).toBe(false);});
 it('deep freezes requirements and procedures with reviewed local real-memory drill',()=>{expect(Object.isFrozen(req.requirements[0])).toBe(true);expect(Object.isFrozen(catalog.checks[0].procedure.commands)).toBe(true);expect(()=>{(req as unknown as {candidateAccepted:boolean}).candidateAccepted=true;}).toThrow();expect(definitions.find(c=>c.id==='memory-continuity')?.available).toBe(true);expect(catalog.validatorIdentity).toBeNull();expect(catalog.activationAllowed).toBe(false);});
 it('maps every approved requirement to checks or global validation rules, with unique definitions',()=>{const mapped=new Set([...catalog.globalRequirements,...definitions.flatMap(c=>c.requirements)]);expect(req.requirements.every(r=>mapped.has(r.id))).toBe(true);expect(new Set(definitions.map(c=>c.id)).size).toBe(9);expect(new Set(definitions.map(c=>c.definitionDigest)).size).toBe(9);});
 it('denies unavailable host before reads and caller-supplied authority/acceptance metadata',async()=>{expect((await evaluate(p,request)).eligible).toBe(false);const f=fixture();expect((await evaluate(p,{...request,candidateAccepted:true},f.authority)).reason).toBe('invalid_requirements_request');expect(f.calls).toHaveLength(0);});
 it('keeps candidate acceptance and environment blocked even if fixtures claim all passes',async()=>{const f=fixture(),r=await f.run();expect(r.eligible).toBe(false);expect(r.checks.find(c=>c.id==='memory-continuity')?.status).toBe('pass');expect(f.calls).toContain('memory-continuity');expect('blockers' in r&&r.blockers).toEqual(expect.arrayContaining(['candidate_owner_acceptance_required','environment_not_authorized']));expect(r.activationAllowed).toBe(false);});
 it.each(definitions.filter(c=>c.available).map(c=>c.id))('required %s missing never satisfies readiness',async id=>{const f=fixture();f.reports.delete(id);const r=await f.run();expect(r.eligible).toBe(false);expect(r.checks.find(c=>c.id===id)?.status).toBe('missing');});
 it.each(['fail','blocked','not_run','skipped'] as const)('does not promote %s results',async outcome=>{const f=fixture();f.reports.get('core-regression')!.outcome=outcome;const r=await f.run();expect(r.checks.find(c=>c.id==='core-regression')?.status).toBe(outcome);expect(r.eligible).toBe(false);});
 it.each(['skippedCases','failedCases','executedCases'] as const)('denies forged passing summary with bad %s',async field=>{const f=fixture();f.reports.get('core-regression')![field]=field==='executedCases'?0:1;const r=await f.run();expect(r.checks.find(c=>c.id==='core-regression')?.status).not.toBe('pass');});
 it.each(['ownerId','projectKey','candidateDigest','environmentId','requirementsDigest','catalogDigest','definitionDigest','reportType'] as const)('denies verified receipt wrong %s binding',async field=>{const f=fixture();(f.reports.get('core-regression') as unknown as Record<string,unknown>)[field]=field.endsWith('Digest')?'c'.repeat(64):'foreign';const r=await f.run();expect(r.checks.find(c=>c.id==='core-regression')?.status).toBe('binding_mismatch');});
 it.each(['requirementsDigest','catalogDigest'] as const)('invalidates a changed %s context before report lookup',async field=>{const f=fixture();f.context[field]='c'.repeat(64);expect((await f.run()).reason).toBe('requirements_or_catalog_changed');expect(f.calls).toHaveLength(0);});
 it.each(['unset','revoked','expired','wrong_scope','implementer'] as const)('denies %s validator designation',async type=>{const f=fixture();if(type==='unset')f.context.validator=null;else if(type==='revoked')f.context.validator!.revoked=true;else if(type==='expired')f.context.validator!.expiresAt=now;else if(type==='wrong_scope')f.context.validator!.projectKey='foreign';else f.context.validator!.actorId=f.context.implementationActorId;expect((await f.run()).reason).toBe('independent_validator_unconfigured_or_invalid');});
 it('denies substituted issuer version and validator standing in for owner walkthrough',async()=>{const f=fixture();f.reports.get('core-regression')!.issuerApprovalVersion=randomUUID();f.reports.get('owner-walkthrough')!.actorId=f.context.validator!.actorId;const r=await f.run();expect(r.checks.find(c=>c.id==='core-regression')?.status).toBe('validator_binding_mismatch');expect(r.checks.find(c=>c.id==='owner-walkthrough')?.status).toBe('owner_acceptance_missing_or_wrong_actor');});
 it('requires current manual acceptance versions without inventing24h owner approval validity',async()=>{const f=fixture();f.reports.get('owner-walkthrough')!.sourceTimestamp=new Date(now-10*86400000).toISOString();expect((await f.run()).checks.find(c=>c.id==='owner-walkthrough')?.status).toBe('pass');f.context.ownerWalkthroughVersion=randomUUID();f.context.independentReviewVersion=randomUUID();const r=await f.run();expect(r.checks.find(c=>c.id==='owner-walkthrough')?.status).not.toBe('pass');expect(r.checks.find(c=>c.id==='independent-security-review')?.status).toBe('independent_review_not_current');});
 it.each([86400000-1,86400000])('uses approved test freshness boundary at %i ms',async offset=>{const f=fixture();f.reports.get('core-regression')!.sourceTimestamp=new Date(now-offset).toISOString();expect((await f.run()).checks.find(c=>c.id==='core-regression')?.status).toBe(offset<86400000?'pass':'expired');});
 it('samples one final time after all reads, rejecting authority changes/unavailable verification',async()=>{const f=fixture();let clockCalls=0;const r=await evaluate(p,request,f.authority,()=>{clockCalls++;return now;});expect(clockCalls).toBe(1);expect(r.eligible).toBe(false);const g=fixture();let reads=0;g.authority.readContext=async()=>{if(++reads===2)g.context.contextVersion=randomUUID();return g.context;};expect((await g.run()).reason).toBe('private_testing_authority_changed');const h=fixture();h.authority.verifyCheck=async()=>{throw new Error('unavailable');};expect((await h.run()).reason).toBe('verified_requirements_records_unavailable');});
 it.each([NaN,Infinity,-1,now+0.5])('denies invalid final clock %s',async value=>{const f=fixture();expect((await evaluate(p,request,f.authority,()=>value)).reason).toBe('invalid_requirements_clock');});
 it('rejects wrong principal/project and future completion without expanding authority',async()=>{const f=fixture();expect((await evaluate({...p,actorId:'foreign'},request,f.authority)).reason).toBe('private_testing_scope_mismatch');expect((await evaluate({...p,projectKey:'personal'},request,f.authority)).reason).toBe('private_testing_project_denied');f.reports.get('core-regression')!.sourceTimestamp=new Date(now+1).toISOString();expect((await f.run()).checks.find(c=>c.id==='core-regression')?.status).toBe('future_receipt');});
 it('rejects raw unverified results or duplicate arrays supplied by a verifier',async()=>{const f=fixture();(f.reports.get('core-regression') as unknown as Record<string,unknown>).provenanceVerified=false;expect((await f.run()).checks.find(c=>c.id==='core-regression')?.status).toBe('invalid_verified_receipt');const g=fixture(),base=g.authority.verifyCheck;g.authority.verifyCheck=async(p,c,e,id)=>id==='core-regression'?[g.reports.get(id),g.reports.get(id)]:base(p,c,e,id);expect((await g.run()).checks.find(c=>c.id==='core-regression')?.status).toBe('invalid_verified_receipt');});
});
