import {afterEach,describe,expect,it,vi} from 'vitest';
import {platformBinding,checkPlatformToken,protectedWorkflowFetch} from '../src/workflow/protected-transport.js';
import {profile,profileEnv} from './fixtures/hosted-profile.js';
import {privateWorkflowRuntime} from '../src/workflow/private-runtime.js';
import {Hono} from 'hono';
export const binding={issuer:'https://oidc.vercel.com/synthetic',audience:'https://vercel.com/synthetic',teamId:'team_synthetic',projectId:'prj_synthetic',environment:'preview'} as const;
const claims=()=>({iss:binding.issuer,aud:binding.audience,owner_id:binding.teamId,project_id:binding.projectId,environment:'preview',exp:Math.floor(Date.now()/1000)+120,nbf:Math.floor(Date.now()/1000)-1});
// Deliberately unsigned unit fixture. Only rejection preflight is under test;
// signature verification is tested by the separate synthetic HTTPS edge.
const token=(changes={})=>Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({...claims(),...changes})).toString('base64url')+'.unitFixture';
const env=()=>({...profileEnv(),BOB_WORKFLOW_PRIVATE_RUNTIME_ENABLED:'true',BOB_WORKFLOW_PROTECTED_TRANSPORT_ENABLED:'true',BOB_WORKFLOW_PLATFORM_BINDING:JSON.stringify(binding)});
afterEach(()=>{vi.unstubAllEnvs();vi.resetModules();});
describe('explicit protected workflow transport',()=>{
 it('defaults off and refuses malformed or production platform binding',()=>{expect(()=>platformBinding({})).toThrow();expect(()=>platformBinding({...env(),VERCEL_ENV:'production'})).toThrow();expect(()=>platformBinding({...env(),BOB_WORKFLOW_PLATFORM_BINDING:'{}'})).toThrow();});
 for(const [label,change] of [['issuer',{iss:'https://foreign.invalid'}],['audience',{aud:'foreign'}],['team',{owner_id:'foreign'}],['project',{project_id:'foreign'}],['environment',{environment:'production'}],['expiry',{exp:1}],['future',{nbf:Math.floor(Date.now()/1000)+3600}]] as const)
  it('rejects wrong '+label+' before network',async()=>{const network=vi.fn();await expect(protectedWorkflowFetch(profile,binding,()=>token(change),network as typeof fetch)(profile.issuer+'/redeem',{method:'POST'})).rejects.toThrow();expect(network).not.toHaveBeenCalled();});
 it('retains owner proof, strips caller platform/bypass headers and acquires per call',async()=>{const getter=vi.fn(()=>token()),network=vi.fn(async(request:Request)=>{expect(request.headers.get('authorization')).toBe('Bearer owner-proof');expect(request.headers.get('cookie')).toBeNull();expect(request.headers.get('x-vercel-protection-bypass')).toBeNull();expect(request.headers.get('x-vercel-oidc-token')).toBeNull();expect(request.headers.get('x-vercel-trusted-oidc-idp-token')).toBe(getter.mock.results.at(-1)?.value);expect(request.redirect).toBe('error');return new Response('{}');});const send=protectedWorkflowFetch(profile,binding,getter,network as typeof fetch);for(let i=0;i<2;i++)await send(profile.coreOrigin+'/v1/governed/bobai',{headers:{authorization:'Bearer owner-proof',cookie:'personal-cookie','x-vercel-protection-bypass':'caller','x-vercel-oidc-token':'caller','x-vercel-trusted-oidc-idp-token':'caller'}});expect(getter).toHaveBeenCalledTimes(2);});
 for(const url of ['http://owner.example.invalid/redeem','https://foreign.invalid/redeem',profile.coreOrigin+'/v1/chat',profile.issuer+'/redeem?leak=1',profile.coreOrigin+'/v1/governed/bobai?unknown=x'])
  it('refuses non-allowlisted target '+url,async()=>{const getter=vi.fn(()=>token());await expect(protectedWorkflowFetch(profile,binding,getter)(url,{method:'POST'})).rejects.toThrow('protected_target_denied');expect(getter).not.toHaveBeenCalled();});
 it('does not follow redirect even when injected transport returns one',async()=>{await expect(protectedWorkflowFetch(profile,binding,()=>token(),(async()=>new Response(null,{status:302,headers:{location:'https://foreign.invalid'}})) as typeof fetch)(profile.issuer+'/issue',{method:'POST'})).rejects.toThrow('protected_redirect_denied');});
 it('missing platform context cannot be supplied by incoming headers and never refreshes',async()=>{vi.stubEnv('VERCEL_OIDC_TOKEN',token());const network=vi.fn();await expect(protectedWorkflowFetch(profile,binding,undefined,network as typeof fetch)(profile.issuer+'/issue',{method:'POST',headers:{'x-vercel-oidc-token':token()}})).rejects.toThrow();expect(network).not.toHaveBeenCalled();});
 it('official helper obtains identity only from trusted server request context',async()=>{const key=Symbol.for('@vercel/request-context'),context=globalThis as unknown as Record<symbol,unknown>,saved=context[key];context[key]={get:()=>({headers:{'x-vercel-oidc-token':token()}})};try{const network=vi.fn(async()=>new Response('{}'));expect((await protectedWorkflowFetch(profile,binding,undefined,network as typeof fetch)(profile.issuer+'/issue',{method:'POST'})).status).toBe(200);expect(network).toHaveBeenCalledOnce();}finally{if(saved===undefined)delete context[key];else context[key]=saved;}});
 it('expiry preflight is not a signature authentication claim',()=>{expect(checkPlatformToken(token(),binding)).toContain('unitFixture');});
});
describe('governed-only private entry',()=>{
 it('default off; malformed private mode never falls back',()=>{expect(privateWorkflowRuntime({})).toBeNull();expect(()=>privateWorkflowRuntime({BOB_WORKFLOW_PRIVATE_RUNTIME_ENABLED:'true'})).toThrow();});
 it('health and governed only; legacy/device/agent/provider surfaces absent',async()=>{const app=privateWorkflowRuntime(env(),()=>new Hono().get('/bobai',c=>c.json({synthetic:true})))!;expect((await app.request('/health')).status).toBe(200);expect((await app.request('/v1/governed/bobai')).status).toBe(200);for(const path of ['/v1/status','/v1/chat','/mcp','/mcp/context','/control-center'])expect((await app.request(path)).status).toBe(404);});
 it('actual deployed entry imports without AI/device/legacy DB configuration',async()=>{for(const [k,v] of Object.entries(env()))vi.stubEnv(k,v);for(const k of ['OPENAI_API_KEY','AI_API_KEY','ZAI_API_KEY','BOB_CORE_DEVICE_TOKEN','DATABASE_URL'])vi.stubEnv(k,'');const {default:app}=await import('../index.js');expect(await (await app.request('/health')).json()).toMatchObject({mode:'private-test',releaseEnabled:false});expect((await app.request('/v1/chat')).status).toBe(404);});
});
