import {describe,it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import {syntheticEvidence,fixtureSource,fixtureDefinition} from '../scripts/lib/evidence-storage-fixture.js';
import {createScopedEvidenceAuthority,sourceIdentitySchema,evidenceBodyDigest} from '../src/workflow/scoped-evidence-source.js';
import {verifyImmutableEvidence} from '../src/workflow/verified-evidence.js';
const run=(f:ReturnType<typeof syntheticEvidence>)=>verifyImmutableEvidence(f.p,{packetId:f.claims.packetId,sourceRecordId:f.claims.sourceRecordId},createScopedEvidenceAuthority(f.reader));
describe('authenticated source and actual report adapters (synthetic producer)',()=>{
 it('verifies exact Ed25519 source/check/report and stable canonical source identity',async()=>{const f=syntheticEvidence();expect((await run(f)).outcome).toBe('pass');expect(evidenceBodyDigest({b:2,a:1})).toBe(evidenceBodyDigest({a:1,b:2}));});
 it('denies missing reader and foreign actor/project before record access',async()=>{const f=syntheticEvidence();await expect(verifyImmutableEvidence(f.p,{packetId:f.claims.packetId,sourceRecordId:f.claims.sourceRecordId},createScopedEvidenceAuthority())).rejects.toThrow();for(const p of [{...f.p,projectKey:'sample'},{...f.p,actorId:'foreign'}])await expect(verifyImmutableEvidence(p,{packetId:f.claims.packetId,sourceRecordId:f.claims.sourceRecordId},createScopedEvidenceAuthority(f.reader))).rejects.toThrow();});
 it.each(['ownerId','projectKey','kind','id','bodyDigest'])('denies record %s substitution',async field=>{const f=syntheticEvidence(),key='source:'+f.c.id,r=f.records.get(key) as Record<string,unknown>;f.records.set(key,{...r,[field]:field==='bodyDigest'?'0'.repeat(64):field==='kind'?'report':'foreign'});await expect(run(f)).rejects.toThrow('evidence_record_scope_or_integrity_mismatch');});
 it.each(['/absolute','../secret','a/../b','a\\b','a//b'])('rejects unsafe manifest path %s',path=>{expect(sourceIdentitySchema.safeParse({...fixtureSource,files:[{path,sha256:'a'.repeat(64)}]}).success).toBe(false);});
 it('rejects changed source and check despite valid claim signature',async()=>{for(const kind of ['source','check'] as const){const f=syntheticEvidence();f.put(kind,kind==='source'?f.c.id:'durability',kind==='source'?{...fixtureSource,patchDigest:'d'.repeat(64)}:{...fixtureDefinition,procedureDigest:'d'.repeat(64)});await expect(run(f)).rejects.toThrow();}});
 it.each(['run','environment','summary','missing','skipped','failure','truncated'])('rejects passing claim with %s report',async mode=>{const f=syntheticEvidence(),raw=JSON.parse(f.report.toString());if(mode==='summary')raw.numTotalTests=2;if(mode==='missing')raw.testResults[0].assertionResults[0].fullName='other case';if(mode==='skipped'){raw.numPassedTests=0;raw.numPendingTests=1;raw.testResults[0].assertionResults[0].status='pending';}if(mode==='failure'){raw.numPassedTests=0;raw.numFailedTests=1;raw.success=false;raw.testResults[0].assertionResults[0].status='failed';}const bytes=mode==='truncated'?Buffer.from('{'):Buffer.from(JSON.stringify(raw));f.claims.reportDigest=createHash('sha256').update(bytes).digest('hex');f.put('report',f.claims.sourceRecordId,{runId:mode==='run'?'foreign':f.claims.runId,environmentDigest:mode==='environment'?'0'.repeat(64):fixtureDefinition.environmentDigest,bytesBase64:bytes.toString('base64')});f.resign();await expect(run(f)).rejects.toThrow();});
 it.each(['fail','not_run'] as const)('preserves authentic outcome %s',async outcome=>{const f=syntheticEvidence(),raw=JSON.parse(f.report.toString());raw.numPassedTests=0;raw.success=false;raw.numFailedTests=outcome==='fail'?1:0;raw.numPendingTests=outcome==='not_run'?1:0;raw.testResults[0].assertionResults[0].status=outcome==='fail'?'failed':'pending';const bytes=Buffer.from(JSON.stringify(raw));f.claims.outcome=outcome;f.claims.reportDigest=createHash('sha256').update(bytes).digest('hex');f.put('report',f.claims.sourceRecordId,{runId:f.claims.runId,environmentDigest:fixtureDefinition.environmentDigest,bytesBase64:bytes.toString('base64')});f.resign();expect((await run(f)).outcome).toBe(outcome);});
 it('denies missing acceptance or issuer',async()=>{const f=syntheticEvidence();f.context.baseline.acceptedByOwner=false;f.put('context',f.claims.packetId,f.context);await expect(run(f)).rejects.toThrow();const g=syntheticEvidence();g.records.delete('issuer:synthetic-ci_synthetic-key');await expect(run(g)).rejects.toThrow();});
});
