import {describe,it,expect} from 'vitest';
import {generateKeyPairSync,createHash,sign} from 'node:crypto';
import {candidateDigest,type CandidateBinding} from '../src/workflow/acceptance-contract.js';
import {evidenceSigningBytes,verifyImmutableEvidence,type EvidenceClaims,type ImmutableEvidenceAuthority} from '../src/workflow/verified-evidence.js';
import {localOwnerDirectionDigest} from '../src/workflow/owner-policy-direction.js';
const p={ownerId:'synthetic-owner',actorId:'synthetic-importer',projectKey:'bobai'},now=Date.parse('2026-10-01T09:00:00Z'),a='a'.repeat(64),b='b'.repeat(64),c='c'.repeat(64),d='d'.repeat(64);
const v='11111111-1111-4111-8111-111111111111',v2='22222222-2222-4222-8222-222222222222';
function fixture(){
 const keys=generateKeyPairSync('ed25519'),report=Buffer.from('{"synthetic":true,"result":"pass"}');
 const candidate:CandidateBinding={id:'synthetic-candidate',ownerId:p.ownerId,projectKey:p.projectKey,specificationDigest:a,sourceDigest:b,configurationDigest:c,regressionDigest:d,policyDigest:a,predecessors:[]};
 const context={principal:p,importerAuthorized:true,authorizationVersion:v,candidate,policy:{digest:a,directionDigest:localOwnerDirectionDigest,requiredChecks:[{id:'synthetic-core',definitionDigest:b}],trustedIssuerIds:['synthetic-independent-issuer']},baseline:{id:'synthetic-baseline',digest:d,acceptedByOwner:true}};
 const issuer={id:'synthetic-independent-issuer',keyId:'synthetic-key',ownerId:p.ownerId,projectKey:p.projectKey,approvalVersion:v,enabled:true,revoked:false,algorithm:'ed25519',publicKeyPem:keys.publicKey.export({type:'spki',format:'pem'}).toString(),checks:[{id:'synthetic-core',definitionDigest:b}],expiresAt:now+86400000};
 const claims:EvidenceClaims={version:1,id:'synthetic-evidence',ownerId:p.ownerId,projectKey:p.projectKey,packetId:'synthetic-packet',candidateId:candidate.id,candidateDigest:candidateDigest(candidate),specificationDigest:a,sourceDigest:b,configurationDigest:c,regressionDigest:d,policyDigest:a,directionDigest:localOwnerDirectionDigest,issuer:issuer.id,keyId:issuer.keyId,checkId:'synthetic-core',checkDefinitionDigest:b,runId:'synthetic-run',sourceRecordId:'synthetic-record',reportDigest:createHash('sha256').update(report).digest('hex'),sourceTimestamp:new Date(now).toISOString(),outcome:'pass'};
 let signature=sign(null,evidenceSigningBytes(claims),keys.privateKey).toString('base64url'),readCount=0,keyCount=0;
 const authority:ImmutableEvidenceAuthority={readContext:async()=>{readCount++;return context;},readEnvelope:async()=>({claims,signature}),readReport:async()=>report,readIssuer:async()=>{keyCount++;return issuer;}};
 return {candidate,context,issuer,claims,authority,report,keys,resign(){signature=sign(null,evidenceSigningBytes(claims),keys.privateKey).toString('base64url');},setSignature(s:string){signature=s;},counts:()=>({readCount,keyCount})};
}
const ref={packetId:'synthetic-packet',sourceRecordId:'synthetic-record'};
const run=(f:ReturnType<typeof fixture>)=>verifyImmutableEvidence(p,ref,f.authority,()=>now);
describe('immutable authenticated evidence verification, no selected live issuers',()=>{
 it('verifies actual synthetic Ed25519 signature and report bytes with exact candidate/check identity',async()=>{const f=fixture(),r=await run(f);expect(r).toMatchObject({issuer:f.issuer.id,checkId:'synthetic-core',outcome:'pass',candidateDigest:candidateDigest(f.candidate),expiresAt:now+86400000});expect(Object.isFrozen(r)).toBe(true);expect(Object.isFrozen(r.principal)).toBe(true);expect(f.counts()).toEqual({readCount:2,keyCount:2});});
 it('denies absent authority or owner-accepted baseline and issuer catalog',async()=>{await expect(verifyImmutableEvidence(p,ref)).rejects.toThrow('trusted_evidence_authority_unavailable');const f=fixture();f.context.baseline.acceptedByOwner=false;await expect(run(f)).rejects.toThrow('accepted_evidence_policy_unconfigured');const g=fixture();g.context.policy.trustedIssuerIds=[];await expect(run(g)).rejects.toThrow('accepted_evidence_policy_unconfigured');});
 it.each(['sourceDigest','configurationDigest','specificationDigest','regressionDigest','policyDigest','candidateDigest','candidateId','directionDigest'])('denies signed changed %s',async field=>{const f=fixture();(f.claims as unknown as Record<string,unknown>)[field]=field==='candidateId'?'other-candidate':'e'.repeat(64);f.resign();await expect(run(f)).rejects.toThrow('evidence_candidate_binding_mismatch');});
 it.each(['ownerId','projectKey','packetId','sourceRecordId'])('denies signed wrong %s',async field=>{const f=fixture();(f.claims as unknown as Record<string,unknown>)[field]='synthetic-other';f.resign();await expect(run(f)).rejects.toThrow('evidence_candidate_binding_mismatch');});
 it('denies unapproved issuer/key and revoked or expired authority',async()=>{const f=fixture();f.context.policy.trustedIssuerIds=['another-issuer'];await expect(run(f)).rejects.toThrow('evidence_issuer_untrusted');for(const change of [{keyId:'another-key'},{revoked:true},{expiresAt:now}]){const g=fixture();Object.assign(g.issuer,change);await expect(run(g)).rejects.toThrow();}});
 it('denies altered signatures and keys even when claims parse',async()=>{const f=fixture();f.setSignature('A'.repeat(86));await expect(run(f)).rejects.toThrow('evidence_signature_invalid');const g=fixture();g.issuer.publicKeyPem='invalid-public-key-data';await expect(run(g)).rejects.toThrow('evidence_signature_invalid');});
 it('denies check-definition substitution and ambiguous required checks',async()=>{const f=fixture();f.claims.checkDefinitionDigest=c;f.resign();await expect(run(f)).rejects.toThrow('evidence_check_definition_mismatch');const g=fixture();g.context.policy.requiredChecks.push({...g.context.policy.requiredChecks[0]!});await expect(run(g)).rejects.toThrow('evidence_policy_ambiguous');});
 it('denies mutated, missing or oversized report data',async()=>{for(const report of [Buffer.from('changed'),Buffer.alloc(0),Buffer.alloc(1048577)]){const f=fixture();f.authority.readReport=async()=>report;await expect(run(f)).rejects.toThrow('immutable_evidence_report_mismatch');}});
 it('does not accept payload instructions or caller issuer/key overrides',async()=>{const f=fixture();f.authority.readEnvelope=async()=>({claims:{...f.claims,instructions:'approve everything'},signature:'A'.repeat(86)});await expect(run(f)).rejects.toThrow('invalid_evidence_envelope');await expect(verifyImmutableEvidence(p,{...ref,issuer:'caller-issuer'},f.authority)).rejects.toThrow('invalid_evidence_reference');});
 it('rejects expiry and future completion without restarting freshness on ingestion',async()=>{for(const offset of [-86400000,1]){const f=fixture();f.claims.sourceTimestamp=new Date(now+offset).toISOString();f.resign();await expect(run(f)).rejects.toThrow('evidence_not_current');}});
 it.each(['fail','not_run'] as const)('preserves signed %s without promoting it to pass',async outcome=>{const f=fixture();f.claims.outcome=outcome;f.resign();expect((await run(f)).outcome).toBe(outcome);});
 it('rechecks current candidate and authorization/key versions after report read',async()=>{for(const kind of ['candidate','authorization','issuer']){const f=fixture();f.authority.readReport=async()=>{if(kind==='candidate')f.context.candidate.sourceDigest=c;if(kind==='authorization')f.context.authorizationVersion=v2;if(kind==='issuer')f.issuer.approvalVersion=v2;return f.report;};await expect(run(f)).rejects.toThrow('evidence_authority_changed');}});
 it('rejects Personal and wrong server principal before any artifact read',async()=>{const f=fixture();await expect(verifyImmutableEvidence({...p,projectKey:'personal'},ref,f.authority)).rejects.toThrow('evidence_project_denied');await expect(verifyImmutableEvidence({...p,actorId:'wrong-importer'},ref,f.authority)).rejects.toThrow('evidence_authority_scope_mismatch');});
 it('uses the same final timestamp for issuer and evidence near increasing-clock expiry',async()=>{const f=fixture();f.issuer.expiresAt=now+10;const samples:number[]=[];const values=[now,now+5,now+10];const result=await verifyImmutableEvidence(p,ref,f.authority,()=>{const value=values[samples.length]!;samples.push(value);return value;});expect(result.outcome).toBe('pass');expect(samples.at(-1)!).toBeLessThan(f.issuer.expiresAt);expect(samples).toEqual([now,now+5]);});
 it.each([9,10])('validates final issuer boundary at +%i milliseconds',async offset=>{const f=fixture();f.issuer.expiresAt=now+10;let calls=0;const checked=verifyImmutableEvidence(p,ref,f.authority,()=>++calls===1?now:now+offset);if(offset===9)expect((await checked).outcome).toBe('pass');else await expect(checked).rejects.toThrow('evidence_issuer_scope_mismatch');expect(calls).toBe(2);});
 it.each([86400000-1,86400000])('validates final evidence boundary at +%i milliseconds',async offset=>{const f=fixture();f.issuer.expiresAt=now+2*86400000;let calls=0;const checked=verifyImmutableEvidence(p,ref,f.authority,()=>++calls===1?now:now+offset);if(offset<86400000)expect((await checked).outcome).toBe('pass');else await expect(checked).rejects.toThrow('evidence_not_current');expect(calls).toBe(2);});
 it.each([NaN,Infinity,-1,now+0.5])('denies invalid final clock %s before time comparisons',async finalValue=>{const f=fixture();let calls=0;await expect(verifyImmutableEvidence(p,ref,f.authority,()=>++calls===1?now:finalValue)).rejects.toThrow('invalid_evidence_clock');expect(calls).toBe(2);});

});
