// Internal fixed-runner producer. Synthetic signing only, never a live issuer/grant.
import {readFile,writeFile,realpath} from 'node:fs/promises';import {createHash,generateKeyPairSync,randomUUID,sign} from 'node:crypto';import {resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {privateVitestCaseIds,privateReportTimes,validatePrivateCheckObservations,privateCheckSigningBytes} from '../src/workflow/private-check-adapters.js';import {privateTestingDefinitions,privateTestingRequirementsDigest,privateTestingCheckCatalogDigest,requirementsDigest} from '../src/workflow/private-testing-requirements.js';
const execute=promisify(execFile),root=process.argv[2];if(process.argv.length!==3||process.env.VERCEL||!/^\/tmp\/bob-workflow-run-[A-Za-z0-9_-]+$/.test(root??''))throw Error('owned_local_fixture_required');
const marker=JSON.parse(await readFile(root+'/SYNTHETIC-ONLY.json','utf8'));if(marker.kind!=='owned-disposable-workflow-fixture'||marker.data!==root+'/workflow-validation/pg-data'||!/^\/tmp\/bob-workflow-pg-[A-Za-z0-9_-]+$/.test(marker.socket))throw Error('owned_marker_invalid');
if(await realpath(root)!==(await realpath('/tmp'))+'/'+root.split('/').at(-1))throw Error('fixture_symlink_denied');if(!/^\/usr\/local\/Cellar\/postgresql@(17|18)\/[A-Za-z0-9._-]+\/bin$/.test(marker.bin)||await realpath(marker.bin)!==marker.bin)throw Error('installed_binary_denied');const status=await execute(marker.bin+'/pg_ctl',['-D',marker.data,'status'],{env:{PATH:'/usr/bin:/bin',LC_ALL:'C'}}).then(()=>false,e=>e.code===3&&String(e.stdout).includes('no server running'));if(!status)throw Error('owned_database_not_stopped');
const declaredInventory=JSON.parse(await readFile(new URL('./lib/private-runner-inventory.json',import.meta.url),'utf8')) as Record<string,string[]>;const localCore=resolve(fileURLToPath(new URL('..',import.meta.url)));const inventory=Object.fromEntries(Object.entries(declaredInventory).map(([suite,cases])=>[suite,cases.map(id=>{if(!id.startsWith('${CORE_ROOT}/tests/')||id.includes('/../'))throw Error('inventory_case_path_denied');return localCore+id.slice('${CORE_ROOT}'.length);})]));const summary=JSON.parse(await readFile(root+'/workflow-validation/runner-receipt.json','utf8'));const ids=['workflow','storage','private-records','recovery'];const names=['postgres','evidence-storage','private-records','recovery'];if(summary.results.length!==4||summary.pending!==0||summary.tcpDisabled!==true||summary.fsync!==true||summary.socket!==marker.socket||summary.binaryDirectory!==marker.bin)throw Error('runner_observation_invalid');
const blob=(v:unknown)=>{const b=Buffer.from(typeof v==='string'?v:JSON.stringify(v));return {sha256:createHash('sha256').update(b).digest('hex'),bytesBase64:b.toString('base64')};};const suites=[];
for(let i=0;i<ids.length;i++){const observed=summary.results[i],path=root+'/workflow-validation/'+names[i]+'.json';if(observed.name!==names[i]||observed.receipt!==path)throw Error('runner_order_invalid');const raw=JSON.parse(await readFile(path,'utf8'));if(raw.success!==true||raw.numFailedTests!==0||raw.numPendingTests!==0||raw.numPassedTests!==inventory[ids[i]!].length||observed.passed!==raw.numPassedTests)throw Error('runner_failed_or_incomplete');if(requirementsDigest(privateVitestCaseIds(raw).slice().sort())!==requirementsDigest(inventory[ids[i]!].slice().sort()))throw Error('predeclared_cases_changed');suites.push({id:ids[i]!,report:blob(raw)});}
// Hash exact declared source bytes, not a caller-supplied candidate claim.
const files=JSON.parse(await readFile(new URL('./lib/private-producer-source-paths.json',import.meta.url),'utf8')) as string[],candidateRoot=resolve(new URL('../..',import.meta.url).pathname);const hashes:Record<string,string>={};for(const p of files){if(!/^(Core|Web|docs|preparation)\//.test(p)&&p!=='implementation.md')throw Error('source_path_denied');if(p.split('/').includes('..'))throw Error('source_path_denied');hashes[p]=createHash('sha256').update(await readFile(resolve(candidateRoot,p))).digest('hex');}
const sourceBefore=JSON.parse(await readFile(root+'/workflow-validation/producer-source-before.json','utf8'));if(requirementsDigest(sourceBefore)!==requirementsDigest(hashes))throw Error('candidate_changed_during_execution');
const sourceDigest=requirementsDigest(hashes),environmentDigest=requirementsDigest({kind:'synthetic-private-unix-postgres',socket:marker.socket,bin:marker.bin,tcpDisabled:true,fsync:true}),keys=generateKeyPairSync('ed25519'),approval=randomUUID();const reports=[];
for(const checkId of ['governed-postgres','encrypted-recovery']){const check=privateTestingDefinitions.find(c=>c.id===checkId)!;const selected=checkId==='encrypted-recovery'?suites.filter(s=>s.id==='recovery'):suites;const raw={version:1,privateSocket:true,tcpDisabled:true,fsync:true,stopped:true,suites:selected};const expected=selected.flatMap(s=>inventory[s.id].map((c:string)=>s.id+':'+c));const parsed=validatePrivateCheckObservations(checkId,raw,expected);if(parsed.counts.failed||parsed.counts.skipped||!parsed.nativeTimes)throw Error('producer_observations_nonpass');const b=blob(raw),claims={version:1,ownerId:'synthetic-owner',projectKey:'bobai',candidateId:'synthetic-producer',candidateDigest:sourceDigest,environmentId:'synthetic-isolated',sourceDigest,environmentDigest,requirementsDigest:privateTestingRequirementsDigest,catalogDigest:privateTestingCheckCatalogDigest,checkId,definitionDigest:check.definitionDigest,procedureDigest:requirementsDigest(check.procedure),caseInventoryDigest:requirementsDigest(expected),reportType:check.reportType,runId:randomUUID(),issuerId:'synthetic-unregistered-validator',keyId:'ephemeral',issuerApprovalVersion:approval,reportDigest:b.sha256,...parsed.nativeTimes,exitCode:0,signal:null};reports.push({checkId,expectedCases:expected,envelope:{claims,signature:sign(null,privateCheckSigningBytes(claims),keys.privateKey).toString('base64url'),bytesBase64:b.bytesBase64},observations:parsed.counts});}
await writeFile(root+'/workflow-validation/producer-observations.json',JSON.stringify({syntheticOnly:true,unregisteredIssuer:true,certification:'not-authorized',activationAllowed:false,sourceDigest,sourceHashes:hashes,publicKeyPem:keys.publicKey.export({type:'spki',format:'pem'}).toString(),reports},null,2),{mode:0o600});console.log(JSON.stringify({syntheticOnly:true,observedReports:reports.map(r=>({checkId:r.checkId,...r.observations})),validation:root+'/workflow-validation'}));
